tm_list = ("cross-functional teams", "cross-functional project team", "feature team", "distributed team", "talented team",
           "fast paced environments", "diverse group", "fast-paced environment", "small and talented team",
           "remote team", "remote teams", "talented team", "tech enthusiasts", "Remote work environment",
           "tight knit team", "team-oriented environment", "cross-functional teams", "fully remote team",
           "Fully remote work")

cp_list = ("FinTech", "banking", "media", "non-profit", "ecommerce", "financial sector", "financial markets", "trading",
           "education", "bootstrapped startup", "boot-strapped start-up", "startup", "crypto", "Games", "social network",
           "fitness", "textile", "digital printing", "bitcoin", "cryptocurrency", "small businesses", "small organization",
           "independent businesses", "consumer energy services", "energy markets", "consumer energy consumption",
           "rental industry")

we_list = ('5+ years of experience', '4 years of professional experience', '2-5 years of experience',
           '2+ years focused on', "a few years of experience", "3-5 years of full-stack experience",
           '2+ years of client-side Javascript experience', '5+ years experience ', '1+ years experience',
           '2 years of professional experience', '2+ years requirement', "2+ years' experience", '3+ years experience',
           '5 years professional development experience', '3+ years of WordPress development experience',
           '2-3 years of software developer experience', '5+ years of professional software development experience',
           '5+ years of industry experience', "3+ years of software engineering experience", '5+ years experience',
           '5+ years previous experience', '3+ years of Drupal experience', "Has least three years of experience",
           '5+ years of directly applicable experience', "5+ years experience",
           '20 years of experience', '5+ years of programming experience', "3-5 years' experience",
           '3+ years in a software engineering or technical architect role', '3+ years of Unity experience',
           '3+ years of Scrum Master experience', 'Significant macOS experience (+5 years)', 'worked for 5+ years',
           '5 years of relevant software development experience', '3-6 years relevant experience',
           '5+ years of PHP experience', '3+ years audio programming experience', "2+ years' experience",
           '5+ years of software development experience', '3-5 years of relevant work experience', '4 years experience',
           '7+ years in the software development industryExperience ', '5 years professional development experience',
           '5+ years of applicable experience', '3+ years of experience', '2 years of Ruby on Rails Experience',
           '3+ years of professional experience', '10+ years of professional engineering experience', '1+ years using',
           '3 years of Ruby on Rails Experience', '5 years of it being Ruby on Rails',
           '4+ years programming experience', "at least two years software development experience",
           '3 years of relevant data development and technology experience', '8+ years programming experience',
           '3+ years of Ruby on Rails experience', '5+ years of professional Front End Development experience',
           "7+ years of Application Development with experience defining development guidelines",
           "1 to 2 years’ experience", "Minimum of 4 years of web app building experience",
           "3+ Years of software development experience", "3+ years of experience",
           "2+ Years of professional Ruby on Rails development experience", "3+ years QA experience",
           "3 to 5 years’ experience with DBMS", '3 to 5 years related work experience',
           "3 to 5 years working knowledge", "5-7 years full stack experience", "3-8+ years",
           "2 years related work experience", '7+ years of progressive work experience',
           '2+ years of DevOps leadership experience', "2+ Years", "7+ years of relevant development experience",
           "5+ years experience", '5+ years of professional experience', '2+ years of experience',
           "3-5+ years work experience", "5+ Years of Real-World Development Experience",
           '3 years of relevant experience', 'Professional experience (hands-on) with ReactJS Framework for 2+ years',
           "3+ years' experience", '2 years experience in PHP', 'Prior experience (at least 3 years)',
           'one year experience', "2+ Years with", "2+ Years of Real-World",
           '3-5 years of experience', 'two years’ experience', '3+ years of DevOps and/or Operations experience',
           '1+ years of production environment experience', '2 years experience developing software')

ge_list = ("strategic and creative thinker", "translate user needs", "English", "researching", "analyzing",
           "problem-solving skills", "fixing issues", "intelligent", "hard-working", "passionate", "evaluating",
           "dream big", "work ethic", "forward thinking", "energetic", "hardworking", "knowledgeable", "positive",
           "empathetic", "Autonomous", "self-starters", "self-ownership", "team-oriented", "Customer Focused",
           "deliver technical requirements", "passion for learning",
           "willingness to learn", "Passion", "enthusiasm", "commitment", "respect", "positive energy",
           "imagination",  "empathy", "adapting to change", "do the hard work", "attention to details",
           "continuously learning", "productivity", "think outside of the box",
           "customer-focused thinking", "self-motivation", "critical thinking", "self-directed learner")

sf_list = ('mentorship', "mentor", "mentoring", 'discussion', 'technical leadership', 'team leadership', "leadership",
           "coordinate", "training", "coaching", "team-player", "coworking", "clear communicator", "collaborative",
           "communication skills", "Communicate", "collaboration", "interface with clients", "soft skills", "accountability",
           "constructive feedback", 'responsible', "active communicator", "collaborate", "responsible", "nurture and grow",
           "communication", "Communication Skills", "team player", "interpersonal skills", "communicating effectively",
           "strong communications skills", "presentation")

of_list = ("competitive compensation", "Competitive compensation", "working from home", "flexible schedule",
           "work from home from anywhere", "telecommute", "2 weeks paid vacation", "ownership", "401(k)", "401K",
           "fostering personal growth", "diverse perspectives", "competitive salaries", "profit sharing", "grow and explore",
           "monthly allowance", "no set hours", "do not limit vacation", "equal opportunity", "healthcare",
           "Work from anywhere", "energizing community", "$2,500 per year", "gym membership", "freedom", "€65k-90k",
           "work with big brands", "6 weeks paid vacation", "health/dental insurance", "inspiration days", "dental",
           "paid holidays", "competitive pay", "Equal Opportunity", "fostering talent", "Flexible vacation",
           "work from anywhere", "solid benefits", "equity", "six-month contract", "option to continue", "30 Hours a Week",
           "high degree of ownership", "operate autonomously", "work from wherever we'd prefer", "Flexible working hours",
           "health, dental and vision insurance", "Flexible vacation policy", "paid holidays", "sick leave",
           "parental leave", "Fitness", "home office credits", "stock options", "Growth and leadership opportunities",
           "independent contractor", "work-life balance", "continuous learning", "Work-Life balance", "30-35€ /h",
           "Flexible schedule and location", "paid vacation", "paid time off", "paid maternity leave",
           "paid paternity/adoption leave", "Education stipend", "monthly budget", "flexibility", "fun work environment",
           "10h - 40h work week", "12-month contract", "40€ /h", "work-from-anywhere", "work-life balance",
           "Competitive salary")
