tm_collection = {
    "cross-functional team": ("cross-functional team", "cross-functional teams", "cross-functional project team"),
    "cross-functional product-oriented squads": ("cross-functional product-oriented squads",),
    "feature team": ("feature team",),
    "distributed team": ("distributed team",),
    "fast-paced environment": ("fast-paced environment", "fast paced environments", "fast-paced"),
    "rapidly changing environment": ("rapidly changing environment", "rapidly changing environments"),
    "diverse group": ("diverse group",),
    "small and talented team": ("small and talented team",),
    "remote team": ("remote team", "remote teams"),
    "talented team": ("talented team",),
    "tech enthusiasts": ("tech enthusiasts",),
    "Remote work": ("Remote work environment", "Remote work", "remote work environment", "remote-friendly environment",
                    "remote-first team", "remote-work environment"),
    "tight-knit team": ("tight-knit team", "tight knit team", "tight-knit engineering team",),
    "team-oriented environment": ("team-oriented environment",),
    "fully remote team": ("fully remote team",),
    "Fully remote work": ("Fully remote work",),
    "remote-first team": ("remote-first team",),
    "stable workplace": ("stable workplace",),
    "Remote-first culture": ("Remote-first culture",),
    "diverse work culture": ("diverse work culture",),
    "highly-skilled team": ("highly-skilled team",),
    "energizing community": ("energizing community",),
    "dynamic team": ("dynamic team", "dynamic teams"),
    "gelled team": ("gelled team", "gelled teams"),
    "Creative Team": ("Creative Team", "Creative team"),
    "Operations Team": ("Operations Team", "Operations team"),
    "Development Team": ("Development Team", "Development team", "development team"),
    "Client Services Team": ("Client Services Team", "Client Services team"),
    "Engineering Team": ("Engineering Team", "engineering team", "teams of engineers"),
    "mobile team": ("mobile team", "mobile teams"),
    "sales and marketing team": ("sales and marketing team", "sales and marketing teams"),
    "fast-moving team": ("fast-moving team", "fast-moving teams"),
    "Dynamic Environment": ("Dynamic Environment", "dynamic environment"),
    "Developer Team": ("Developer Team", "developer team", "developer teams", "team of developers"),
    "Test Team": ("Test Team", "test team"),
    "Enterprise Business Systems Team": ("Enterprise Business Systems Team",),
    "accountable team environment": ("accountable team environment",),
    "Ambiguous environment": ("Ambiguous environment", "ambiguous environment"),
    "project team": ("project team",)
}

cp_collection = {
    "FinTech": ("FinTech",),
    "Media": ("Media", "media"),
    "Nonprofit organization": ("Nonprofit organization", "non-profit"),
    "E-commerce": ("E-commerce", "e-commerce", "ecommerce", "online commerce", "eCommerce", "Ecommerce"),
    "Finance": ("financial sector", "financial markets", "Banking", "banking", "trading", "rental industry",
                "billing services", "financial data", "personal finance management", "Financials",
                "financial institutions"),
    "Education": ("Education", "education", "e-learning"),
    "Startup": ("Startup", "startup", "startups", "bootstrapped startup", "boot-strapped start-up"),
    "Cryptocurrency": ("Cryptocurrency", "cryptocurrency", "crypto", "bitcoin", "Crypto", "Tokenomics"),
    "Games": ("Games",),
    "Social Network": ("Social Network", "social network"),
    "Fitness": ("Fitness", "fitness"),
    "Textile": ("Textile", "textile"),
    "digital printing": ("digital printing",),
    "Small Business": ("Small Business", "small businesses", "small organization", "emerging businesses", "regional business"),
    "Large Enterprises": ("Large Enterprises", "large enterprises"),
    "independent businesses": ("independent businesses",),
    "Energy": ("Energy", "energy", "consumer energy services", "energy markets", "consumer energy consumption",
               "solar power", "solar", "Solar technology"),
    "Medical": ("Medical", "medical", "medical data"),
    "Transportation": ("Transportation", "transportation"),
    "profitable company": ("profitable company",),
    "Marketing": ("Marketing", "marketing", "email marketing",),
    "Highly Regulated Industry": ("Highly Regulated Industry", "highly regulated industry"),
    "Privately-held Company": ("Privately-held Company", "privately-held company"),
    "Advisory Consulting": ("Advisory Consulting", "Advisory consulting"),
    "Healthcare Industry": ("Healthcare Industry", "Healthcare industry"),
    "IT": ("IT", "it")
}

ge_collection = {
    "English": ("English", "english"),
    "problem-solving skills": ("problem-solving skills", "problem solver", "problem-solving capabilities",
                               "Problem-solving mindset", "problem solving skills", "problem-solving abilities",
                               "problem-solvers", "problem solving", "problem-solving", "problem solvers"),
    "decision-making skills": ("decision-making skills", "decision-making skill"),
    "customer-focused thinking": ("customer-focused thinking", "Customer-focused thinking",),
    "forward thinking": ("forward thinking", "Forward thinking",),
    "passion for learning": (
        "passion for learning", "willingness to learn", "continuously learning", "self-directed learner",
        "constantly learning", "continuous learner", "Continuously learn", "continuous improvement"
    ),
    "strategic and creative thinker": ("strategic and creative thinker", "think outside of the box"),
    "organizational skills": ("organizational skills",),
    "Passion": ("Passion", "passion",),
    "Empathy": ("Empathy", "empathy",),
    "adapting to change": ("adapting to change", "adapting to changes",),
    "hard-workers": ("do the hard work", "do the hard works", "hard-workers"),
    "attention to details": ("attention to details", "attention to detail"),
    "Productivity": ("productivity", "Productivity",),
    "critical thinking": ("critical thinking", "Critical thinking",),
    "dream big": ("dream big", "Dream big",),
    "work ethic": ("work ethic", "Work ethic",),
    "positive energy": ("positive energy", "Positive energy"),
    "deliver technical requirements": ("deliver technical requirements", "Deliver technical requirements",),
    "commitment": ("commitment", "Commitment",),
    "Self-starter": ("Self-starter", "self-starters", "self-starter"),
    "self-ownership": ("self-ownership", "self ownership", ),
    "passionate individual": ("passionate individual", "passionate individuals"),
    "Respect": ("Respect", "respect"),
    "Imagination": ("Imagination", "imagination"),
    "Enthusiasm": ("Enthusiasm", "enthusiasm"),
    "Self-motivation": ("Self-motivation", "self-motivation"),
    "Self-management": ("Self-management", "self-management"),
    "Attitude": ("Attitude", "good attitude"),
    "Analytical Skills": ("Analytical Skills", "analytical skills")
}

sf_collection = {
    "soft skills": ("soft skills", "Soft skills",),
    "Communication Skills": ("Communication Skills", "Communication skills", "excellent communicator",
                             "strong communications skills", "communication skills", "communication",
                             "communicating effectively", "clear communicator", "active communicator",
                             "Communication", "good communicator", "good communication", "excellent communication skills",
                             "excellent written and oral communication", "communications skills", "verbal and written communications skills",
                             "verbal and written communication", "Excellent communication skills", "Good communication"),
    "interpersonal skills": ("interpersonal skills", "interpersonal skill"),
    "mentorship": ("mentorship", "mentor", "mentoring", "approachable mentors", "Mentor"),
    "coaching": ("coaching", "Coaching",),
    "team-player": ("team-player", "team player", "Team player"),
    "collaboration": ("collaboration", "Collaboration", "collaborative attitude"),
    "constructive feedback": ("constructive feedback",),
    "accountability": ("accountability", "Accountability",),
    "co-working": ("co-working", "coworking"),
    "interface with clients": ("interface with clients", "Interface with clients",),
    "Discussion": ("Discussion", "discussion"),
    "Presentation": ("Presentation", "presentation", "presentation skills"),
    "Leadership": ("Leadership", "leadership", "leadership", "technical leadership", "team leadership"),
    "Responsibility": ("Responsibility", "responsibility"),
    "teamwork": ("teamwork", "teamwork", "team skills"),
    "coordination skills:": ("coordination skills", "coordination skill")
}

of_collection = {
    "competitive compensation": ("competitive compensation", "Competitive compensation", "competitive salaries",
                                 "competitive pay", "Competitive salary", "great salary pack", "Competitive base salary",
                                 "compensation package"),
    "independent contractor": ("independent contractor", "Independent contractor",),
    "operate autonomously": ("operate autonomously", "Operate autonomously",),
    "solid benefits": ("solid benefits", "Solid benefits",),
    "Work-Life balance": ("Work-Life balance", "work-life balance", "30 Hours a Week", "10h - 40h work week",
                          "work life balance"),
    "flexibility": ("flexible schedule", "Flexible schedule and location", "Flexible working hours",
                    "Flexible vacation policy", "Flexible vacation", "flexibility", "no set hours", "freedom",
                    "flexible working hours", "Flexible Work", "flexible work hours"),
    "paid vacation": ("paid vacation", "2 weeks paid vacation", "6 weeks paid vacation", "Generous vacation policy",
                      "company holidays", "12-week paid leave", "paid maternity leave", "parental leave", "PTO",
                      "paid paternity/adoption leave", "sick leave", "paid time off", "paid parental leave",
                      "Paid time off"),
    "stipend": ("stipend", "Education stipend", "development stipend", "monthly budget"),
    "401(k)": ("401(k)", "401K", "401 (K)"),
    "telecommute": ("work from home from anywhere", "telecommute"),
    "personal growth": ("fostering personal growth", "work with big brands", "Growth and leadership opportunities",
                        ),
    "insurance": ("insurance", "health/dental insurance", "health, dental and vision insurance", "Health insurance",
                  "health insurance", "healthcare"),
    "Equal Opportunity": ("Equal Opportunity", "equal opportunity", "equal employment opportunities"),
    "Equity": ("Equity", "profit sharing", "stock options", "Stock options", "equity", "Competitive equity"),
    "diverse perspectives": ("diverse perspectives",),
    "Money": ("$2,500 per year", "40€ /h", "€65k-90k", "$70k - 100k", "$80k - 100k", "$100k - 135k", "$100k - 150k",
              "$95k - 145k", "€55k - 104k", "$105k - 110k"),
    "gym membership": ("gym membership", "Gym membership"),
    "Contract": ("Contract", "contract"),
    "high degree of ownership": ("high degree of ownership",),
    "option to continue": ("option to continue",),
    "Paid relocation": ("Paid relocation", "paid relocation"),
    "Learning opportunities": ("Learning opportunities", "learning opportunities", "opportunities to learn"),
    "Health Benefits": ("Health Benefits", "Health benefits", "Health and Wellness programs", "medical program"),
    "Contractor": ("Contractor", "Contractors"),
    "Generous bonuses": ("Generous bonuses", "generous bonuses")
}

we_collection = {
    "Work Experience": ("Work Experience", "experience", "work experience", "Experience", "Working Experience", "working experience"),
    "Full-Stack experience": ("Full-Stack experience", "full-stack experience", "full stack experience"),
    "Web App building experience": ("Web App building experience", "web app building experience"),
    "Real-World Development Experience": ("Real-World Development Experience", "Real World Development Experience"),
    "Software Development Experience": ("Software Development Experience", "Development Experience", "development experience",
                                        "software development experience",),
    "Professional Experience": ("Professional Experience", "professional experience", "professional software development experience"),
    "Industry experience": ("Industry experience", "industry experience"),
    "Coding experience": ("Coding experience", "coding experience"),
    "Full years experience": ("Full years experience", "full years experience"),
    "Related experience": ("Related experience", "related experience", "relevant experience"),
    "Hands-on experience": ("Hands-on experience", "hands-on experience", "Demonstrated experience", "hands on experience"),
    "Equivalent Experience": ("Equivalent Experience", "equivalent experience")
}
