"""Key: the standard word, Value: collection of other format of standard word"""


pl_collection = {
    "JavaScript": ("JavaScript", "Javascript", "javascript", "JS", "JAVASCRIPT", "Javascrpt"),
    "ECMAScript": ("ECMAScript", "ecmascript", "ES2015", "ES2016", "ES2017", "ES2018", "ES5", "ES6", "ES7", "ES8",
                   "EcmaScript"),
    "TypeScript": ("TypeScript", "Typescript", "typescript"),
    "CoffeeScript": ("CoffeeScript", "Coffeescript"),
    "Babel": ("Babel", "babel"),
    "Java": ("Java", "java", "Java8", "Java 8", "Java11", "Java 7", "JAVA"),
    "Python": ("Python", "python", "python3", "Python3", "PYTHON"),
    "Ruby": ("Ruby", "ruby"),
    "CRuby": ("CRuby", "C-ruby"),
    "JRuby": ("JRuby", "C-ruby", "Jruby"),
    "PHP": ("PHP", "php", "PHP7", "PHP 5"),
    "C": ("C", "c"),
    "C++": ("C++", "c++", "cpp"),
    "C#": ("C#", "c#"),
    "Objective-C": ("Objective-C", "Objective C", "objective-c", "Obj-C"),
    "Swift": ("Swift", "swift", "SWIFT"),
    "Kotlin": ("Kotlin", "kotlin", ),
    "Go": ("Go", "go", "Golang", "GoLang", "GO"),
    "Rust": ("Rust", "rust", "RUST"),
    "Perl": ("Perl", "perl", "PERL"),
    "Erlang": ("Erlang", "erlang"),
    "Groovy": ("Groovy", "groovy"),
    "JVM": ("JVM", "jvm"),
    "Scala": ("Scala", "scala"),
    "Elixir": ("Elixir", "elixir"),
    "Cython": ("Cython", "cython", "CPython", "CPython"),
    "Jython": ("Jython", "jython"),
    "Clojure": ("Clojure", "clojure"),
    "Lua": ("Lua", "lua"),
    "DSLs": ("DSLs", "dsls"),
    "VB.NET": ("VB.NET", "vb.net"),
    "R": ("R", "r"),
    "JSX": ("JSX", "Jsx"),
    "Dart": ("Dart", "dart")
}
ol_collection = {
    "HTML": ("HTML", "html", "HTML5", "HTML4"),
    "CSS": ("CSS", "css", "CSS3", "Cascade Styling Sheets", "flexbox"),
    "XML": ("XML", "xml", "XSD", "XSL"),
    "XSLT": ("XSLT", "xslt"),
    "Bash": ("Bash", "bash", "Bash Shell", "BASH", "shell"),
    "SCSS": ("SCSS", "scss"),
    "SASS": ("SASS", "sass", "Sass"),
    "GraphQL": ("GraphQL", "graphQL"),
    "SQL": ("SQL", "sql"),
    "Jinja": ("Jinja", "Jinja2"),
    "DOM": ("DOM", "dom"),
    "PowerShell": ("PowerShell", "powershell"),
    "WebAssembly": ("WebAssembly", "Wasm", "wasm"),
    "TOML": ("TOML", "toml"),
    "Less.js": ("Less", "less", "LESS"),
    "LINQ": ("LINQ", "Language Integrated Query"),
    "RAML": ("RAML", "raml"),
    "WSDLs": ("WSDLs", "WSDLS"),
    "Dataweave": ("Dataweave", "dataweave"),
    "Stylus": ("Stylus", "stylus"),
    "SAML": ("SAML", "Security Assertion Markup Language")
}
lb_collection = {
    "React": ("React", "react", "React.js", "react.js", "React JS", "ReactJS", "React Hooks", "REACT", "Reactjs", "ReactJs"),
    "React-router": ("React-router",),
    "Redux": ("Redux", "redux"),
    "React-Redux": ("React-Redux", "react-redux"),
    "jQuery": ("jQuery", "jquery", "JQuery", "Jquery"),
    "Pandas": ("Pandas", "pandas"),
    "Numpy": ("Numpy", "numpy"),
    "SciPy": ("SciPy", "scipy"),
    "scikit-learn": ("scikit-learn", "Scikit-learn"),
    "Matplotlib": ("Matplotlib", "matplotlib"),
    "Pytorch": ("Pytorch", "pytorch", "torch"),
    "Scrapy": ("Scrapy", "scrapy"),
    "PySpark": ("PySpark", "Pyspark"),
    "Bootstrap": ("Bootstrap", "bootstrap", "Bootstrap 3", "Bootstrap 4", "Bootstrap 5"),
    "React-Bootstrap": ("React-Bootstrap", "React-bootstrap"),
    "Material UI": ("Material UI", "Material-UI", "Material", "material"),
    "Elasticsearch": ("Elasticsearch", "ElasticSearch", "elasticsearch", "elastic search"),
    "iText": ("iText", "itext", ),
    "Dask": ("Dask", "dask"),
    "Immutable.js": ("Immutable.js", "immutable.js",),
    "RxJS": ("RxJS", "rxJS",),
    "RxJava": ("RxJava", "Rxjava", "rxJava"),
    "RxSwift": ("RxSwift", "rxSwift"),
    "Stanford CoreNLP": ("Stanford CoreNLP", "Stanford coreNLP",),
    "OpenNLP": ("OpenNLP", "openNLP",),
    "NLTK": ("NLTK", "nltk",),
    "EventMachine": ("EventMachine", "eventMachine",),
    "Socket.IO": ("Socket.IO", "socket.IO",),
    "Axios": ("Axios", "axios"),
    "Leaflet.js": ("Leaflet.js", "leaflet.js"),
    "leaflet-google.js": ("leaflet-google.js", "leaflet-google", "leaflet google"),
    "SQLAlchemy": ("SQLAlchemy", "SqlAlchemy"),
    "SockJS": ("SockJS", "Sockjs"),
    "ReactiveX": ("ReactiveX", "reactiveX"),
    "LibAdblockPlus": ("LibAdblockPlus", "libadblockplus"),
    "Backbone.js": ("Backbone.js", "Backbone"),
    "Lightweight": ("Lightweight", "Lightweight Java Game Library")
}
fw_collection = {
    "Flask": ("Flask", "flask"),
    "Django": ("Django", "django"),
    "Django Rest Framework": ("Django Rest Framework", "DRF"),
    "Angular": ("Angular", "AngularJS", "Angular.js", "angular", "Angular 6", "Angular 2"),
    "Ruby on Rails": ("Ruby on Rails", "Rails", "RoR", "ruby-on-rails"),
    "Laravel": ("Laravel", "Laravel 5", "Laravel 5.4"),
    "Vue.js": ("Vue.js", "VueJS", "Vue"),
    "Vuetify": ("Vuetify", "vuetify",),
    "ASP.NET": ("ASP.NET", "asp.net", "Asp.net", "Asp.Net", "ASP.Net", "asp.NET", "asp.Net"),
    ".NET": (".NET", ".Net",),
    "React Native": ("React Native", "React native", "React-Native", "react-native"),
    "PHPUnit": ("PHPUnit", "PHPunit"),
    "Ember.js": ("Ember.js", "Ember", "ember", "EmberJs", "ember.js"),
    "Mocha": ("Mocha", "mocha"),
    "Flutter": ("Flutter", "flutter"),
    "MyBatis": ("MyBatis", "mybatis"),
    "Hibernate": ("Hibernate", "hibernate"),
    "Cypress": ("Cypress", "Cypress.io"),
    "Selenium": ("Selenium", "selenium", "Selenium Web Driver"),
    "JAXB": ("JAXB", "Jaxb"),
    "Jest": ("Jest", "jest", "JEST"),
    "Spark": ("Spark", "Apache Spark", "spark"),
    "WatchKit": ("WatchKit", "watchKit",),
    "XCTest": ("XCTest", "XCtest",),
    "Web Forms": ("Web Forms", "WebForms",),
    "Express.js": ("Express.js", "Express"),
    "Hadoop": ("Hadoop", "hadoop", "Apache Hadoop"),
    "Ext.js": ("Ext.js", "Extjs", "ExtJS"),
    "Foundation": ("Foundation", "Foundation 5"),
    "Drupal": ("Drupal", "drupal", "drupal-8"),
    "knockout": ("knockout", "knockout.js", "KnockoutJS"),
    "Pyramid": ("Pyramid", "pyramid"),
    "Vert.x": ("Vert.x", "Vertx"),
    "Substrate": ("Substrate", "substrate"),
    "ZK": ("ZK", "zk"),
    "Jasmine": ("Jasmine", "jasmine"),
    "Protractor": ("Protractor", "protractor"),
    "JUnit": ("JUnit", "JUnit4", "JUnit5"),
    "Spring": ("Spring", "spring", "Spring Framework", "Spring framework"),
    "Spring Boot": ("Spring Boot", "Spring boot"),
    "Spring Cloud": ("Spring Cloud", "Spring cloud"),
    "Spring Security": ("Spring Security", "Spring security"),
    "WPF": ("WPF", "wpf"),
    "Entity Framework": ("Entity Framework", "Entity framework"),
    "Swagger": ("Swagger", "swagger"),
    "PhoneGap": ("PhoneGap", "Adobe PhoneGap"),
    "Apache Cordova": ("Apache Cordova", "Cordova"),
    "Lumen": ("Lumen", "lumen"),
    "Zend Framework": ("Zend Framework", "ZendFramework"),
    "Sails.js": ("Sails.js", "Sails"),
    "NUnit": ("NUnit", "Nunit"),
    "PyTest": ("PyTest", "Pytest"),
    "REST Assured": ("REST Assured", "RestAssured")
}
ds_collection = {
    "Database": ("Database", "database", "databases", "Databases"),
    "Relational Database": ("Relational Database", "relational database", "Relational database", "RDBMS",
                            "relational databases", "sql database"),
    "Non-relational Database": ("Non-relational Database", "non-relational database", "Non-relational database"),
    "NoSQL": ("NoSQL", "nosql", "NoSql", "NOSQL", "nosql database"),
    "MySQL": ("MySQL", "mysql", "Mysql"),
    "InnoDB": ("InnoDB", "innodb"),
    "PostgreSQL": ("PostgreSQL", "Postgresql", "Postgres", "postgresql"),
    "MariaDB": ("MariaDB", "Mariadb"),
    "Oracle": ("Oracle", "oracle"),
    "ClustrixDB": ("ClustrixDB", "clustrixdb"),
    "MongoDB": ("MongoDB", "mongodb", "mongo", "Mongo"),
    "DynamoDB": ("DynamoDB", "Dynamo"),
    "Redis": ("Redis", "redis"),
    "Microsoft SQL Server": ("Microsoft SQL Server", "MS SQL", "MSSQL", "mssql", "SQLServer"),
    "Apache Phoenix": ("Apache Phoenix", "Phoenix"),
    "Memcached": ("Memcached", "memcached"),
    "Apache HBase": ("Apache HBase", "HBase", "HBASE"),
    "Apache Cassandra": ("Apache Cassandra", "Cassandra"),
    "Firebase": ("Firebase", "firebase"),
    "Firestore": ("Firestore", "firestore"),
    "Presto": ("Presto", "PrestoDB"),
    "RTDB": ("RTDB", "rtdb"),
    "Varnish": ("Varnish", "VARNISH"),
    "SQL Server": ("SQL Server", "sql-server"),
    "RDMS": ("RDMS", "rdms"),
    "Apache Hive": ("Apache Hive", "Hive", "HIVE"),
    "Apache Impala": ("Apache Impala", "Impala"),
    "DB2": ("DB2", "db2"),
    "Data Warehouse": ("Data Warehouse", "Data warehouse"),
    "MapReduce": ("MapReduce", "mapReduce"),
    "Ehcache": ("Ehcache", "EHCache")
}
dt_collection = {
    "JSON": ("JSON", "json", "Json"),
    "GSON": ("GSON", "Gson"),
    "RabbitMQ": ("RabbitMQ", "rabbitMQ"),
    "Kafka": ("Kafka", "kafka", "KAFKA"),
    "Data Pipeline": ("Data Pipeline", "data pipelines", "Data pipelines"),
    "Message Queueing": ("Message Queueing", "message queueing", "Message queueing", ),
    "Database Migration": ("Database Migration", "database migrations", "Database migrations"),
    "Sqoop": ("Sqoop", "sqoop"),
    "Messaging Services": ("Messaging Services", "Messaging Service"),
    "JMS": ("JMS", "jms", "Java Messaging Services"),
    "ORM": ("ORM", "Object-relational mapping"),
    "JPA": ("JPA", "Jpa"),
    "Celery": ("Celery", "celery"),
    "JDBC": ("JDBC", "jdbc")
}
os_collection = {
    "Linux": ("Linux", "linux"),
    "Ubuntu": ("Ubuntu", "ubuntu"),
    "Android": ("Android", "android"),
    "iOS": ("iOS", "ios", "IOS"),
    "Windows": ("Windows", "windows"),
    "Windows Server": ("Windows Server", "windows server"),
    "CentOS": ("CentOS", "centOS"),
    "Redhat": ("Redhat", "redhat"),
    "macOS": ("macOS", "MacOS", "OS X"),
    "Unix": ("Unix", "unix", "UNIX"),
    "Virtual Machine": ("Virtual Machine", "virtual machine", "virtual machines", "VM", "Virtual Machines"),
    "LXC": ("LXC", "lxc"),
    "watchOS": ("watchOS", "watch-os"),
    "GNU": ("GNU", "gnu"),
    "Openwrt": ("Openwrt", "openwrt"),
    "RTOS": ("RTOS", "Real-time operating system"),
}
sv_collection = {
    "Sever": ("Server", "server"),
    "Nginx": ("Nginx", "nginx", "NGINX"),
    "Node.js": ("Node.js", "node.js", "NodeJS", "Node", "node", "Nodejs", "Node.JS", "Node JS"),
    "Jetty": ("Jetty", "jetty"),
    "CDN": ("CDN", "cdn"),
    "Cluster": ("Cluster", "cluster", "clusters"),
    "HAProxy": ("HAProxy", "HaProxy"),
    "Bare Metal": ("Bare Metal", "Bare-metal server"),
    "Tomcat": ("Tomcat", "tomcat"),
    "JBoss": ("JBoss", "Jboss"),
    "Servlet": ("Servlet", "Servlets"),
    "JavaServer Pages": ("JavaServer Pages", "JSP")
}
tl_collection = {
    "Building System": ("Building System", "Building Systems"),
    "Jenkins": ("Jenkins", "jenkins"),
    "TeamCity": ("TeamCity", "teamcity"),
    "Gradle": ("Gradle", "gradle"),
    "npm": ("npm", "NPM"),
    "Maven": ("Maven", "maven"),
    "RubyGems": ("RubyGems", "rubygems"),
    "Git": ("Git", "git", "GIT"),
    "Subversion": ("Subversion", "subversion",),
    "Grunt": ("Grunt", "grunt"),
    "Slack": ("Slack", "slack"),
    "WordPress": ("WordPress", "wordpress", "Wordpress"),
    "Jetpack": ("Jetpack", "jetpack",),
    "WooCommerce": ("WooCommerce", "Woocommerce",),
    "webpack": ("webpack", "Webpack"),
    "Aspose": ("Aspose", "Aspose API"),
    "debugger": ("Debugger", "debugger"),
    "IDE": ("IDE", "ide"),
    "IntelliJ IDEA": ("IntelliJ IDEA",),
    "Skype": ("Skype", "skype"),
    "Photoshop": ("Photoshop", "photoshop"),
    "PayPal": ("PayPal", "paypal"),
    "Stripe": ("Stripe", "stripe"),
    "Pivotal Tracker": ("Pivotal Tracker", "pivotal tracker"),
    "AVA": ("AVA", "ava",),
    "Terraform": ("Terraform", "terraform"),
    "Ansible": ("Ansible", "ansible",),
    "Matillion": ("Matillion", "matillion"),
    "Bugzilla": ("Bugzilla", "bugzilla"),
    "JIRA": ("JIRA", "Jira"),
    "AppKit": ("AppKit", "Appkit"),
    "Crashlytics": ("Crashlytics", "crashlytics"),
    "Bitrise": ("Bitrise", "bitrise",),
    "Fastlane": ("Fastlane", "fastlane",),
    "Zeplin": ("Zeplin", "zeplin",),
    "Wireframes": ("Wireframes", "wireframes",),
    "Trello": ("Trello", "trello"),
    "DeepDive": ("DeepDive", "Deepdive",),
    "Google Hangouts": ("Google Hangouts", "Google hangouts",),
    "Saltstack": ("Saltstack", "saltstack",),
    "Codeship": ("Codeship", "codeship"),
    "Mapbox": ("Mapbox", "mapbox"),
    "ESRI": ("ESRI", "esri"),
    "Visual Studio": ("Visual Studio", "Visual studio", "visual-studio-2019", "visual-studio-2017", "visual-studio"),
    "productivity tools": ("productivity tools", "Productivity tools",),
    "Vagrant": ("Vagrant", "vagrant"),
    "Puppet": ("Puppet", "puppet"),
    "Marionette": ("Marionette", "marionette"),
    "Gmail": ("Gmail", "gmail"),
    "Okta": ("Okta", "okta"),
    "Adblock Plus": ("Adblock Plus", "Adblock plus", "ABP"),
    "Adblock Browser": ("Adblock Browser", "Adblock browser"),
    "Flattr": ("Flattr", "flattr"),
    "SDK": ("SDK", "SDKs", "sdk"),
    "Chromium": ("Chromium", "chromium"),
    "OpenBadges": ("OpenBadges", "openBadges"),
    "Blockcerts": ("Blockcerts", "blockcerts"),
    "Healthkit": ("Healthkit", "healthkit"),
    "Bower": ("Bower", "bower"),
    "gulp.js": ("gulp.js", "gulp", "Gulp"),
    "Build Tool": ("Build Tool", "build tools"),
    "Nexus Repository": ("Nexus Repository", "Nexus"),
    "Udeploy": ("Udeploy", "udeploy"),
    "Apigee": ("Apigee", "apigee"),
    "SOAPUI": ("SOAPUI", "SoapUI"),
    "Splunk": ("Splunk", "splunk"),
    "CruiseControl": ("CruiseControl", "cruiseControl"),
    "WebSphere": ("WebSphere", "IBM WebSphere"),
    "pip": ("pip", "PIP"),
    "Confluence": ("Confluence", "confluence"),
    "Cucumber": ("Cucumber", "Cucumber Testing")
}
at_collection = {
    "REST": ("REST", "RESTful API", "RESTful APIs", "REST API", "REST APIs", "RESTful", "Restful APIs",
             "Representational state transfer", "Restful", "RESTFUL"),
    "Microservices": ("Microservices", "microservices", "Microservice", "microservice", "Micro-Services"),
    "Message-based communication": ("Message-based communication", "message-based communication",),
    "Serverless": ("Serverless", "serverless", ),
    "Distributed Systems": ("Distributed Systems", "distributed systems", "Distributed systems", "distributed-system"),
    "Distributed Databases": ("Distributed Databases", "distributed databases", "distributed databases", "Distributed Database"),
    "distributed Networking": ("distributed Networking", "distributed networking"),
    "Zookeeper": ("Zookeeper", "zookeeper"),
    "MVC": ("MVC", "mvc"),
    "MVVM": ("MVVM", "mvvm"),
    "Cloud Architecture": ("Cloud Architecture", "cloud architecture", "Cloud architecture"),
    "Flux": ("Flux", "flux", ),
    "LAMP": ("LAMP", "Lamp"),
    "Middleware": ("Middleware", "middleware"),
    "Architecture": ("Architecture", "architecture", "architecture solutions", "architecture definition"),
    "Architecture Diagrams": ("Architecture Diagrams", "architecture diagrams",),
    "Architecture Review": ("Architecture Review", "architecture review", "architecture reviews"),
    "System Design": ("System Design", "system design"),
    "Client/Server architecture": ("Client/Server architecture", "Client-Server architecture"),
    "software Architecture": ("software Architecture", "software architecture"),
    "SOA": ("SOA", "soa"),
    "Mean Stack": ("Mean Stack", "mean stack"),
    "Ajax": ("Ajax", "AJAX"),
    "EJB": ("EJB", "ejb")
}
ap_collection = {
    "Agile": ("Agile", "agile"),
    "Scrum": ("Scrum", "scrum", "SCRUM", "scrums"),
    "Extreme Programming": ("Extreme Programming", "XP", ),
    "Kanban": ("Kanban", "kanban", "KANBAN"),
    "GitFlow": ("GitFlow", "Gitflow", "gitflow"),
    "Continuous Integration": ("Continuous Integration", "CI", "Continuous integration", "continuous integration",
                               "continuous-integration"),
    "Continuous Delivery": ("Continuous Delivery", "CD", "continuous delivery"),
    "Continuous Deployment": ("Continuous Deployment", "Continuous Deployments", "continuous deployment"),
    "Sprint": ("Sprint", "sprint", "sprints"),
    "CI/CD": ("CI/CD", "CD/CI"),
    "Test-Driven Development": ("Test-Driven Development", "Test-driven development", "TDD", "test-driven development",
                                "Test Driven Development", "test driven development"),
    "Behavior-driven development": ("Behavior-driven development", "BDD", ),
    "Business Driven Development": ("Business Driven Development",),
    "Test Automation": ("Test Automation", "test automation", "Test automation", "automated testing", "automated tests",
                        "automated-tests", "automated test", "automation testing", "Automated testing"),
    "E2E testing": ("E2E testing", "End-to-End testing", "end-to-end testing"),
    "continuous testing": ("continuous testing", "Continuous testing"),
    "Unit testing": ("Unit testing", "unit testing", "Unit Testing", "unit tests", "Unit Tests", "unit test",
                     "Unit-testing", "test at unit"),
    "Integration Testing": ("Integration Testing", "integration testing"),
    "Automated Configuration": ("Automated Configuration", "Automated configuration"),
    "Automatic Backups": ("Automatic Backups", ),
    "build automation": ("build automation", "Build automation"),
    "Waterfall model": ("Waterfall", "waterfall"),
    "pair-programming": ("pair-programming", "Pair-programming"),
    "code-review": ("code-review", "code-reviews", "code reviews", "code review", "Review code", "Review", "peer review", "peer reviews",),
    "SOLID": ("SOLID", "SOLID principle", "SOLID principles"),
    "DRY": ("DRY", "DRY principle"),
    "DDD": ("DDD", "DDD principle", "Domain Driven Design"),
    "KISS": ("KISS", "KISS principle"),
    "Technical Principles": ("Technical Principles", "technical principles", "Technical principles", "coding principles"),
    "development techniques": ("development techniques", "Development techniques",),
    "auto-scaling": ("auto-scaling", "Auto-scaling", ),
    "regression test": ("regression test", "Regression Test"),
    "testing principles": ("testing principles", "Testing principles",),
    "UITests": ("UITests", "UItests",),
    "software reliability analyses": ("software reliability analyses", "Software reliability analyses"),
    "Technical Best Practices": ("Technical Best Practices", "technical best practises", "best practices", ),
    "Coding Standards": ("Coding Standards", "coding standards"),
    "Engineering Standards": ("Engineering Standards", "Engineering standards", "engineering standards"),
    "Development Standards": ("Development Standards", "development standards"),
    "ALM": ("ALM", "Application lifecycle management"),
    "CRM": ("CRM", ),
    "User Acceptance Testing": ("User Acceptance Testing", "UAT"),
    "Production Acceptance Testing": ("Production Acceptance Testing", "PAT"),
    "Feature Testing": ("Feature Testing", "Feature Test"),
    "Testing Methodology": ("Testing Methodology", "testing methodology"),
    "Reactive Coding Principles": ("Reactive Coding Principles", "reactive coding principles"),
    "team meetings": ("team meetings", "meetings")
}
se_collection = {
    "Design Patterns": ("Design Patterns", "design patterns", "Design patterns"),
    "Object-oriented Programming": ("Object-oriented Programming", "object-oriented programming", "OOP",
                                        "object-oriented view", "OOPS", "Object oriented programming", "object-oriented view",
                                        "object-oriented design", "object-oriented software development", "object-oriented",
                                        "object-oriented concepts"),
    "Requirement": ("Requirement", "requirements"),
    "logging": ("logging", "Logging"),
    "profiling": ("profiling", "Profiling"),
    "integration": ("integration", "integrations", "integrate", "Integration"),
    "build": ("build", ),
    "refactoring": ("refactoring", "Refactoring"),
    "documentation": ("documentation", "Documentation"),
    "caching": ("caching", "Caching"),
    "debugging": ("debugging", "Debugging"),
    "scaling": ("scaling", "scaling"),
    "testing": ("testing", "Testing", "test"),
    "planning": ("planning", "plan"),
    "test planning": ("test planning", "test plan"),
    "designing": ("designing", "Designing", "product design", "technical design"),
    "Modular Design": ("Modular Design", "modular design"),
    "Development": ("Development", "Developing", "developing", "development", "software development", "software engineering",
                    "Software Engineering", "Software Development", "application development", "Application Development",
                    "Application Management", "project development"),
    "maintaining": ("maintaining", "Maintaining", "maintain"),
    "performance analysis": ("performance analysis", "Performance analysis",),
    "optimisation": ("optimisation", "optimisations", "optimize"),
    "performance optimization": ("performance optimization", "performance optimisation", "Performance Optimization",
                                 "performance improvement", "performance improvements"),
    "Deployment": ("Deployment", "deployment", "deployments", "deploy"),
    "Version Control": ("Version Control", "version control", "VCS", "Source Control", "Source control",
                        "source control", "Source Code Control", "Source Code Management",),
    "Troubleshooting": ("Troubleshooting", "troubleshooting", "Troubleshoot", "troubleshoot"),
    "monitoring": ("monitoring", "Monitoring"),
    "maintenance": ("maintenance", "Maintenance"),
    "Support": ("Support", "support"),
    "Merging": ("Merging", "merging"),
    "Code optimization": ("Code optimization", "Code optimization"),
    "enhance": ("enhance", "enhancing"),
    "implementation": ("implementation", "Implementation"),
    "client-side routing": ("client-side routing", ),
    "dynamic code loading": ("dynamic code loading", ),
    "code branching": ("code branching", "branching", ),
    "fixing bugs": ("fixing bugs", "Fixing bugs"),
    "Quality Improvements": ("Quality Improvements", "quality improvements", "Quality improvements"),
    "Tech Debt": ("Tech Debt", "tech debt", "tech debt balance", "Tech debt balance"),
    "performance issues": ("performance issues", "Performance issues", ),
    "troubleshoot complex issues": ("troubleshoot complex issues", "Troubleshoot complex issues", ),
    "roadmap priorities": ("roadmap priorities", "Roadmap priorities",),
    "functional requirements": ("functional requirements", "Functional requirements", ),
    "design specifications": ("design specifications", "Design specifications", "design guidelines"),
    "issue-tracking": ("issue-tracking", "Issue-tracking",),
    "Authentication": ("Authentication", "authentication"),
    "Internationalisation": ("Internationalisation", "internationalisation", "internationalization", "Internationalization",),
    "stream processing": ("stream processing", "Stream processing",),
    "Data Processing": ("Data Processing", "Data processing", "data processing",),
    "Data Model": ("Data Model", "data model", "data model", "data modeling"),
    "automated processes": ("automated processes", "Automated processes",),
    "rapid iteration": ("rapid iteration", "Rapid iteration",),
    "software development life cycle": ("software development life cycle", "Software development life cycle",
                                        "project life cycle", "development cycle", "software development cycle"),
    "Load Balancing": ("Load Balancing", "Load balancing",),
    "design mockups": ("design mockups", "Design mockups",),
    "technical feasibility": ("technical feasibility", "Technical feasibility",),
    "design concepts": ("design concepts", "Design concepts",),
    "Performance Tweaking": ("Performance Tweaking", "performance tweaking"),
    "Infrastructure Design": ("Infrastructure Design", "infrastructure design"),
    "Data Modelling": ("Data Modelling", "data modelling"),
    "User Experience": ("User Experience", "User Experiences", "user experience"),
    "Functional Programming": ("Functional Programming", "functional programming"),
    "Requirement Document": ("Requirement Document", "requirement documents"),
    "Dependency Management": ("Dependency Management", "dependency management", "dependencies"),
    "Database Design": ("Database Design", "database design"),
    "System Development Life Cycle": ("System Development Life Cycle", "Systems development life cycle", "SDLC"),
    "App Releases": ("App Releases", "app releases"),
    "algorithmic design": ("algorithmic design", ),
    "iteration": ("iteration",)
}
pf_collection = {
    "Cloud Platforms": ("Cloud Platforms", "Cloud platforms", "cloud technologies", "cloud platforms", "Cloud", "cloud development",
                        "cloud service", "cloud services", "Cloud services", "Cloud Servers", "cloud"),
    "cloud-based systems": ("cloud-based systems", "cloud-based systems", "cloud-based technologies"),
    "AWS": ("AWS", "aws", "Amazon Web Services", "amazon-web-services", "Amazon"),
    "GCP": ("GCP", "Google Cloud Platform", "GOOGLE CLOUD", "Google Cloud", "google-cloud-platform", "Google cloud infra"),
    "Azure": ("Azure", "Microsoft Azure", "azure", ),
    "Salesforce": ("Salesforce", "salesforce"),
    "Heroku": ("Heroku", "heroku"),
    "DigitalOcean": ("DigitalOcean", "Digitalocean"),
    "Pivotal Cloud Foundry": ("Pivotal Cloud Foundry", "PCF", "Pivotal Cloud"),
    "GitHub": ("GitHub", "github", "Github"),
    "GitLab": ("GitLab", "gitLab", "gitlab", "Gitlab"),
    "Docker": ("Docker", "docker"),
    "Kubernetes": ("Kubernetes", "kubernetes", "Kubernates"),
    "Unity": ("Unity", "unity"),
    "Bitbucket": ("Bitbucket", "bitbucket"),
    "Apache Solr": ("Apache Solr", "Solr"),
    "Amazon Redshift": ("Amazon Redshift", "Amazon redshift", "Redshift",),
    "Amazon S3": ("Amazon S3", "S3", "s3"),
    "AWS Glue": ("AWS Glue", "AWS glue"),
    "AWS Pipeline": ("AWS Pipeline", "AWS pipeline"),
    "Amazon EC2": ("Amazon EC2", "EC2", "ec2"),
    "Amazon RDS": ("Amazon RDS", "RDS", "AWS RDS"),
    "BrowserStack": ("BrowserStack", "browserstack", "browser stack"),
    "Google APIs": ("Google APIs", "Google API", ),
    "Athena": ("Athena", "Athena",),
    "Ionic": ("Ionic", "Ionic 4"),
    "Snowflake": ("Snowflake", "snowflake"),
    "Looker": ("Looker", "looker"),
    "Apache Arrow": ("Apache Arrow",),
    "Xamarin": ("Xamarin",),
    "Amazon Turk": ("Amazon Turk",),
    "VPC": ("VPC", "vpc",),
    "Amazon Route 53": ("Amazon Route 53", "Route53", "route53",),
    "AWS Lambda": ("AWS Lambda", "Lambda", "lambda"),
    "Amazon CloudFront": ("Amazon CloudFront", "CloudFront", "Cloudfront"),
    "Amazon SNS": ("Amazon SNS", "SNS", "sns"),
    "AWS Elastic Beansalk": ("AWS Elastic Beansalk", "Elastic Beansalk",),
    "AWS API Gateway": ("AWS API Gateway", "aws-api-gateway"),
    "Packer": ("Packer", "packer"),
    "OpenShift": ("OpenShift", "Openshift"),
    "OpenCerts": ("OpenCerts", "openCerts"),
    "DFinity": ("DFinity", "dFinity"),
    "Ethereum": ("Ethereum", "ethereum"),
    "Polkadot": ("Polkadot", "polkadot"),
    "ECC": ("ECC", "Ecc"),
    "Dapp": ("Dapp", "dApp"),
    "Google Fit": ("Google Fit", "Google fit"),
    "CUDA": ("CUDA", "cuda"),
    "J2EE": ("J2EE", "j2ee", "J2ee", "JEE"),
    "MuleSoft": ("MuleSoft", "Mulesoft", "mulesoft"),
    "iTunes": ("iTunes", "itunes"),
    "Google Play": ("Google Play", "Google play"),
    "Perfecto Mobile": ("Perfecto Mobile", "Perfecto mobile"),
    "Sauce Labs": ("Sauce Labs", "Sauce labs", "Saucelab"),
    "Experitest": ("Experitest", "experitest"),
    "Magento": ("Magento", "magento"),
}
dv_collection = {
    "Front-end": ("Front-end", "frontend", "front-end development", "front-end", "Frontend", "front end"),
    "Back-end": ("Back-end", "Backend", "backend", "back-end", "backends", "back end", "server-side"),
    "Full Stack": ("Full Stack", "full stack", "Full-stack"),
    "Security": ("Security", "security"),
    "Cyber Security": ("Cyber Security", "cyber security"),
    "QA": ("QA", "qa", "Quality Management"),
    "Product Management": ("Product Management", "product management"),
    "Project Management": ("Project Management", "project management", "Project management"),
    "UI": ("UI", "UIs", "UI designs", "user interface"),
    "UX": ("UX", "UXs", "UX design"),
    "UI/UX": ("UI/UX", "UI/UX Design", "UI/UX design", "UX/UI"),
    "Design": ("Design", "design", "designs"),
    "DevOps": ("DevOps", "Devops", "devops", "dev ops", "DeVops", "Tech Ops", "DevOPs", "devOps"),
    "Big Data": ("Big Data", "Big data", "large-scale data", "Large-scale data", "large datasets", "Large datasets"),
    "Data Engineering": ("Data Engineering", "data engineering"),
    "3D Animation": ("3D Animation", "3D animation"),
    "Image Processing": ("Image Processing", ),
    "Data Analytics": ("Data Analytics", "data analytics"),
    "Data Science": ("Data Science", "data science", "Data science", "data-science"),
    "Site Reliability": ("Site Reliability", "site reliability", ),
    "Data Infrastructure": ("Data Infrastructure", "data infrastructure"),
    "Network Infrastructure": ("Network Infrastructure", "network infrastructure", "Network infrastructure",),
    "Large-scale network": ("Large-scale network", "large-scale network"),
    "Infrastructure Engineering": ("Infrastructure Engineering", "infrastructure engineering"),
    "Automation": ("Automation", "automation",),
    "Cloud-security": ("Cloud-security", "cloud-security", "Cloud Platform Security", "Cloud Platform security"),
    "Hardware Engineering": ("Hardware Engineering", "hardware engineering"),
    "System Administration": ("System Administration", "System Admin")
}
ps_collection = {
    "Front-end Engineer": ("Front-end Engineer", "Front-end Engineer", "frontend engineers", "Frontend Engineers",
                           "Front-End Engineer"),
    "Front-end Developer": ("Front-end Developer", "front-End Developer", "front end developer", "Frontend Developers",
                            "front-end developers", "FRONT END WEB DEVELOPER", "Front End Developer", "frontend developers",
                            "Front-End Developer"),
    "Back-end Engineer": ("Back-end Engineer", "back-end Engineers", "Back End Engineers", "Backend Software Engineer",
                          "back-end engineer", "Back-End Software Engineer"),
    "Back-end Developer": ("Back-end Developers", "Back End Developers", "back-end developers", "Back-End Developer",
                           "back-end developer", "Backend Developer", "Back End Developer"),
    "Full Stack Engineer": ("Full Stack Engineer", "Full-Stack Engineer", "full stack engineer", "full-stack engineer",
                            "Full Stack Software Engineers", "Full-stack Software Engineer"),
    "Full Stack Developer": ("Full Stack Developer", "full stack software developer", "full stack developers",
                             "Full Stack Developers", "full-stack developers", "Full Stack developer",
                             "Full Stack Web Developers", "Full-Stack Web Developer", "Full Stack Software Developer"),
    "Software Developer": ("Software Developer", "software developer", "Developer", "Developers", "developer", "developers",
                           "software developers"),
    "Software Engineer": ("Software Engineer", "Software Engineers", "software engineer", "software engineers", "engineers",
                          "engineer", "Engineer", "Engineers", "Staff Software Engineer"),
    "Software Architect": ("Software Architect", "Architect", "architect", "architects", "Architects"),
    "Senior Software Architect": ("Senior Software Architect", "Senior Software Architects"),
    "Web Developer": ("Web Developer", "web developer"),
    "DevOps Engineer": ("DevOps Engineer", "DevOps Engineers", "DevOps engineers"),
    "Game Developer": ("Game Developer", "Game developer"),
    "Data Engineer": ("Data Engineer", "Data Engineers", "data engineer"),
    "Data Developer": ("Data Developer", "Data Developers"),
    "Data Scientist": ("Data Scientist", "data scientist", "data scientists", "Data Scientists"),
    "Data Analyst": ("Data Analyst", "Data Analysts"),
    "Big Data Developer": ("Big Data Developer", "Big Data developer"),
    "Product Manager": ("Product Manager", "product manager", "product managers", "PM", "Product Managers", "Product manager"),
    "Project Manager": ("Project Manager", "project manager", "Technical Project Manager", "Technical Manager"),
    "Product Designer": ("Product Designer", "Product Designers", "product designers"),
    "Designer": ("Designer", "Designers", "designers", "designer"),
    "UI/UX Designer": ("UI/UX Designer", "UI/UX designer"),
    "UX Engineer": ("UX Engineer", "UX Engineers", "UX designer"),
    "Test Engineers": ("Test Engineers", "test engineers"),
    "Tester": ("Tester", "testers", "QA Tester", "QA tester", "Sr Automation Tester"),
    "QA Engineer": ("QA Engineer", "QA engineer", "QA engineers", "QA Automation Engineer"),
    "QA Specialist": ("QA Specialist", "QA specialists"),
    "Scrum Master": ("Scrum Master", "Scrum Masters", "Scrum master", "Scrum masters"),
    "Business Analyst": ("Business Analyst", "business analysts", "Business Analysts"),
    "Software Consultant": ("Software Consultant", "software consultant"),
    "Mobile Engineer": ("Mobile Engineer", "mobile engineer"),
    "Mobile Developer": ("Mobile Developer", "Mobile Developers"),
    "Desktop Engineer": ("Desktop Engineer", "Desktop engineers"),
    "Senior Back-end Developer": ("Senior Back-end Developer", "Senior Backend Developer", "Senior Backend Developers",
                                  "senior backend developer"),
    "Senior Back-end Engineer": ("Senior Back-end Engineer", "Senior Backend Engineer", "Senior Backend Engineers",
                                 "senior backend engineer"),
    "Senior Front-end Developer": ("Senior Front-end Developer", "Senior Frontend Developer", "Senior Frontend Developers"),
    "Senior Front-end Engineer": ("Senior Front-end Engineer", "Senior Frontend Engineer", "Senior Frontend Engineers",
                                  "Senior Front End Engineer", "Senior Front-End Engineer", "Senior Frontend Software Engineer"),
    "Senior Software Developer": ("Senior Software Developer", "Senior Developer", "Senior Developers", "Senior developers",
                                  "senior developer"),
    "Senior Software Engineer": ("Senior Software Engineer", "senior software engineer", "Sr. Software Engineer",
                                 "Senior Engineer", "senior engineer", "Senior Software Engineers", "Senior Engineers"),
    "Senior DevOps Engineer": ("Senior DevOps Engineer", "Sr. DevOps Engineer"),
    "Senior Data Scientist": ("Senior Data Scientist", "Senior Data Scientists"),
    "Quality Engineering Manager": ("Quality Engineering Manager", "Quality Engineering Managers"),
    "Software Support Engineer": ("Software Support Engineer", "Software Support Engineers"),
    "Technical Lead": ("Technical Lead", "Technical Leader", "technical leader", "Tech Lead"),
    "CEO": ("CEO", "ceo"),
    "CTO": ("CTO", "cto"),
    "CFO": ("CFO", "cfo"),
    "Director of Engineering": ("Director of Engineering", "Director of engineering", ),
    "code reviewers": ("code reviewers", "Code reviewers",),
    "Junior Developers": ("Junior Developers", "junior developers", "Jr. Software Developer", "entry-level software developer"),
    "Junior Engineers": ("junior engineers", "junior engineers"),
    "Lead Developer": ("Lead Developer", "lead developer", "Lead Application Developer", "Lead Application Developer", "Lead Application Developers",
                       "Lead Engineer"),
    "Lead UI Developer": ("Lead UI Developer", "Lead UI Developers"),
    "Director of Operations": ("Director of Operations", "director of operations"),
    "Senior Systems Developer": ("Senior Systems Developer", "Senior Systems Developers"),
    "Professional Services Consultant": ("Professional Services Consultant", "Professional Services Consultants"),
    "Lead DevOps Engineer": ("Lead DevOps Engineer", "Lead DevOps engineer", ),
    "System Administrator": ("System Administrator", "system administrator", "sysadmin"),
    "Team Lead": ("Team Lead", "Team lead"),
    "Project Lead": ("Project Lead", "Project lead"),
    "Analyst": ("Analyst", "Analysts"),
    "Release Engineer": ("Release Engineer", "Release Engineers"),
    "Programmer": ("Programmer", "programmer")
}
cs_collection = {
    "Computer Science": ("Computer Science", "computer science", "computer engineering", "Computer Engineering"),
    "Information Systems": ("Information Systems", "Information System"),
    "Data Structure": ("Data Structure", "data structure"),
    "Algorithms": ("Algorithms", "algorithms", "Algorithm", "Algorithmic"),
    "Data Structures": ("Data Structures", "data structures"),
    "Mathematics": ("Mathematics", "mathematics"),
    "Statistics": ("Statistics", "statistics"),
    "Concurrency": ("Concurrency", "concurrency", "concurrent programming"),
    "Multithreading": ("Multithreading", "multithreaded"),
    "Multiprocessing": ("Multiprocessing", "multiprocessing"),
    "Parallelism": ("Parallelism", "parallelism"),
    "Asynchronous": ("Asynchronous", "asynchronous"),
    "Cryptography": ("Cryptography", "cryptography"),
    "Computability": ("Computability", "computability"),
    "Computer Architecture": ("Computer Architecture", "computer architecture"),
    "Chunking": ("Chunking", "chunking"),
    "Ethernet": ("Ethernet", "ethernet"),
    "DNS": ("DNS", "dns"),
    "VPN": ("VPN", "vpn"),
    "Networking": ("Networking", "networking"),
    "Network": ("Network", "networks", "network"),
    "Routing": ("Routing", "routing"),
    "routers": ("routers", "Routers"),
    "switches": ("switches", "Switches"),
    "PoP": ("PoP", "POP"),
    "Virtual LAN": ("Virtual LAN", "VLANs"),
    "Computational Complexity": ("Computational Complexity", "computational complexity"),
    "Consensus": ("Consensus", "consensus"),
    "BLS": ("BLS", "BLS signature scheme", "Boneh–Lynn–Shacham"),
    "Firmware": ("Firmware", "firmware"),
    "Embedded Controller": ("Embedded Controller", "Embedded Controllers"),
    "SSD": ("SSD", "Solid-state drive"),
    "Flash Memory": ("Flash Memory", "Flash memory"),
    "NAND": ("NAND", "NAND gate"),
    "Semiconductor": ("Semiconductor", "Semi- Conductors"),
    "Information Technology": ("Information Technology", "information technology"),
    "Multi-threading": ("Multi-threading", "multi-threading")
}
ai_collection = {
    "AI": ("AI", "Artificial Intelligence", "artificial intelligence"),
    "Machine Learning": ("Machine Learning", "Machine learning", "machine learning", "machine-learning"),
    "Deep Learning": ("Deep Learning", "Deep learning"),
    "NLP": ("NLP", "Natural Language Processing", "natural language processing"),
    "Text Classification": ("Text Classification", "text classification"),
    "Sentiment Analysis": ("Sentiment Analysis", "sentiment analysis", "Sentiment analysis"),
    "NER": ("NER", "named-entity recognition"),
    "CNN": ("CNN", "convolutional neural network"),
    "Transfer Learning": ("Transfer Learning", "transfer learning"),
    "artificial general intelligence": ("artificial general intelligence",),
    "AI Ethics": ("AI Ethics", "ai Ethics"),
    "model training": ("model training", "training", ),
    "labelling": ("labelling", "Labelling"),
    "Bayesian Forecasting Models": ("Bayesian Forecasting Models", "Bayesian forecasting models"),
    "Computer Vision": ("Computer Vision", "computer vision", "computer-vision", "computer vision technology")
}
pt_collection = {
    "Messaging Protocols": ("Messaging Protocols", "messaging protocols", ),
    "Protocol Buffers": ("Protocol Buffers", "protocol buffers"),
    "TCP": ("TCP", "tcp"),
    "TCP/IP": ("TCP/IP", "tcp/ip"),
    "IP": ("IP", "ip"),
    "UDP": ("UDP", "udp"),
    "HTTP": ("HTTP", "http", "Http"),
    "HTTPs": ("HTTPs", "https"),
    "WebSocket": ("WebSocket", "WebSockets"),
    "API": ("API", "APIs", "api"),
    "CORS": ("CORS", "cors"),
    "SSL": ("SSL", "ssl"),
    "SSH": ("SSH", "ssh"),
    "Paxos": ("Paxos", "paxos"),
    "FTP": ("FTP", "ftp"),
    "SFTP": ("SFTP", "sftp"),
    "TLS": ("TLS", "tls"),
    "SOAP": ("SOAP", "soap"),
    "BGP": ("BGP", "bgp"),
    "Contentful": ("Contentful", "contentful"),
    "DHCP": ("DHCP", "dhcp"),
    "VRRP": ("VRRP", "vrrp"),
    "VLANs": ("VLANs", "vlans"),
    "IGP": ("IGP", "igp"),
    "ECMP": ("ECMP", "ecmp"),
    "OSPF": ("OSPF", "ospf"),
    "MPLS": ("MPLS", "mpls"),
    "RSVP": ("RSVP", "rsvp"),
    "LDP": ("LDP", "ldp"),
    "APN": ("APN", "apn"),
    "SNMP": ("SNMP", "snmp"),
    "Modbus": ("Modbus", "modbus"),
    "IPv4": ("IPv4", "IPV4"),
    "IPv6": ("IPv6", "IPv6"),
    "DisplayPort protocol": ("DisplayPort protocol", "DP"),
    "OAuth": ("OAuth", "oauth"),
    "Kerberos": ("Kerberos",),
    "JWT": ("JWT", "jwt"),
}

pd_collection = {
    "Web Application": ("Web Application", "Web application", "web application", "web applications", "web-app",
                        "web technology", "web technologies", "website", "websites", "web", "Web", "web-technology",
                        "web-services", "web apps", "web services", "webapp", "Web Services", "responsive web pages",
                        "responsive web design", "Web-based applications"),
    "Single-page Application": ("Single-page Application", "single-page application", "single-page-application",
                                "single page application", "SPA", "single-page web application"),
    "Software as a service": ("Software as a service", "SaaS", "SAAS", "SaaS technology", "SaaS apps", "saas"),
    "Enterprise Applications": ("Enterprise Applications", "enterprise applications", "enterprise class applications",),
    "Open-source Software": ("Open-source Software", "Open-source software", "open source", "open-source", "Open source",
                             "open source software"),
    "Mobile App": ("Mobile App", "Mobile app", "Mobile", "mobile", "mobile platform", "mobile applications", "mobile app"),
    "Desktop Application": ("Desktop Application", "desktop", "Desktop"),
    "Small and Medium Scale Systems": ("Small and Medium Scale Systems", "Small and medium scale systems",),
    "Large-scale Systems": ("Large-scale Systems", "Large-scale systems", "large-scale systems", ),
    "Third Party Technologies": ("Third Party Technologies", "third party technologies", "Third party technologies",
                                 "third-party checkout", "third-party APIs", "third-party billing services", "3rd party APIs",
                                 "3rd party apps", "3rd party system", "Third Party systems"),
    "High Traffic Applications": ("High Traffic Applications", "high traffic applications", "High traffic applications",),
    "Analysis Engines": ("Analysis Engines", "analysis engines", "Analysis engines",),
    "Data Driven Application": ("Data Driven Application", "data driven application", "data driven applications",
                                "data-oriented products"),
    "Profitable Project": ("Profitable Project", "profitable project", "profitable projects"),
    "Legacy System": ("Legacy System", "legacy system"),
    "Video Games": ("Video Games", "video games"),
    "Chrome Extension": ("Chrome Extension", "chrome extensions"),
    "Decentralized solution": ("Decentralized solution", "decentralized solution"),
    "Enterprise-grade messaging infrastructure": ("Enterprise-grade messaging infrastructure", "enterprise-grade messaging infrastructure"),
    "Prototype": ("Prototype", "prototypes"),
    "Distributed Message System": ("Distributed Message System", "distributed message systems"),
    "High-end Systems Engineering": ("High-end Systems Engineering", "high-end systems engineering"),
    "Embedded System": ("Embedded System", "embedded systems"),
    "customized technology solutions": ("customized technology solutions", )
}

ql_collection = {
    "Scalability": ("Scalability", "scalability", "Scalable development workflow", "scalable development workflow",
                    "Scalable Backend Systems", "scalable backend systems", "scalable systems", "highly scalable"),
    "Testability": ("Testability", "testability"),
    "Stability": ("Stability", "stability"),
    "high-quality code": ("high-quality code", "high-quality"),
    "Reliability": ("Reliability", "reliability", "reliable code",),
    "High Performance": ("High Performance", "high-performance", "high performance code", "performance", "high performing"),
    "Supportability": ("Supportability", "supportability"),
    "Maintainability": ("Maintainability", "maintainability", "code maintainability"),
    "Modularity": ("Modularity", "modularity", "modular code"),
    "Ambiguity": ("Ambiguity", "ambiguity"),
    "Data Integrity": ("Data Integrity", "data integrity"),
    "Code Quality": ("Code Quality", "code quality"),
    "High Quality": ("High Quality", "high quality", "High quality",),
    "Speed": ("Speed", "speed", "maximum speed"),
    "Consistency": ("Consistency", "consistency"),
    "Accessibility": ("Accessibility", "accessibility"),
    "High Availability": ("High Availability", "High availability", "highly-available"),
    "Reusable Code": ("Reusable Code", "reusable code", "Reusable code", "reusable components"),
    "Maintainable Systems": ("Maintainable Systems", "maintainable systems", "Maintainable systems",),
    "System Performance": ("System Performance", "system performance", "System performance",),
    "Cross-browser Compatibility": ("Cross-browser Compatibility", "cross-browser compatibility", "Cross-browser compatibility",),
    "Cross-device Compatibility": ("Cross-device Compatibility", "cross-device compatibility", "Cross-device compatibility",),
    "Efficient Processes": ("Efficient Processes", "efficient processes", "Efficient processes",),
    "High-quality Software": ("High-quality Software", "high-quality software", "High-quality software"),
    "Accuracy": ("Accuracy", "accuracy"),
    "Latency": ("Latency", "latency", "low latency",),
    "Complexity": ("Complexity", "complexitiy", "complexities"),
    "Monolithic Code": ("Monolithic Code", "monolithic code"),
    "Highly-cohesive": ("Highly-cohesive", "highly-cohesive"),
    "Loosely-coupled": ("Loosely-coupled", "loosely-coupled"),
    "Performance Bottlenecks": ("Performance Bottlenecks", "performance bottlenecks"),
    "Highly Available Service": ("Highly Available Service", ),
    "scalable and performance oriented services": ("scalable and performance oriented services",)
}
