pl_collection = {
    "JavaScript": ("JavaScript", "Javascript", "javascript", "JS"),
    "ECMAScript": ("ECMAScript", "ecmascript", "ES2015", "ES2016", "ES2017", "ES2018", "ES5", "ES6", "ES7", "ES8",
                   "EcmaScript"),
    "TypeScript": ("TypeScript", "Typescript", "typescript"),
    "CoffeeScript": ("CoffeeScript", "Coffeescript"),
    "Babel": ("Babel", "babel"),
    "Java": ("Java", "java", "Java8", "Java11"),
    "Python": ("Python", "python"),
    "Ruby": ("Ruby", "ruby"),
    "PHP": ("PHP", "php", "PHP7"),
    "C": ("C", "c"),
    "C++": ("C++", "c++", "cpp"),
    "C#": ("C#", "c#"),
    "Objective-C": ("Objective-C", "Objective C", "objective-c", "Obj-C"),
    "Swift": ("Swift", "swift"),
    "Kotlin": ("Kotlin", "kotlin"),
    "Go": ("Go", "go", "Golang", "GoLang"),
    "Rust": ("Rust", "rust"),
    "Perl": ("Perl", "perl"),
    "Erlang": ("Erlang", "erlang"),
    "Groovy": ("Groovy", "groovy"),
    "JVM": ("JVM", "jvm"),
    "Scala": ("Scala", "scala"),
    "Elixir": ("Elixir", "elixir"),
    "Cython": ("Cython", "cython", "CPython", "CPython"),
    "Jython": ("Jython", "jython"),
    "Clojure": ("Clojure", "clojure"),
    "Lua": ("Lua", "lua"),
    "DSLs": ("DSLs", "dsls"),
    "VB.NET": ("VB.NET", "vb.net"),
    "R": ("R", "r"),
}
ol_collection = {
    "HTML": ("HTML", "html", "HTML5"),
    "CSS": ("CSS", "css", "CSS3"),
    "XML": ("XML", "xml"),
    "Bash": ("Bash", "bash", "Bash Shell", "BASH", "shell"),
    "SCSS": ("SCSS", "scss"),
    "SASS": ("SASS", "sass", "Sass"),
    "GraphQL": ("GraphQL", "graphQL"),
    "SQL": ("SQL", "sql"),
    "Jinja": ("Jinja", "Jinja2"),
    "DOM": ("DOM", "dom"),
    "PowerShell": ("PowerShell", "powershell")
}
lb_collection = {
    "React": ("React", "react", "React.js", "react.js", "React JS", "ReactJS", "React Hooks"),
    "Redux": ("Redux", "redux"),
    "React-Redux": ("React-Redux", "react-redux"),
    "jQuery": ("jQuery", "jquery", "JQuery", "Jquery"),
    "Pandas": ("Pandas", "pandas"),
    "Numpy": ("Numpy", "numpy"),
    "SciPy": ("SciPy", "scipy"),
    "scikit-learn": ("scikit-learn", "Scikit-learn"),
    "Matplotlib": ("Matplotlib", "matplotlib"),
    "Pytorch": ("Pytorch", "pytorch", "torch"),
    "Scrapy": ("Scrapy", "scrapy"),
    "PySpark": ("PySpark", "Pyspark"),
    "Spring": ("Spring", "spring"),
    "Spring Boot": ("Spring Boot", "Spring boot"),
    "Bootstrap": ("Bootstrap", "bootstrap"),
    "React-Bootstrap": ("React-Bootstrap", "React-bootstrap"),
    "Material UI": ("Material UI", "Material-UI", ),
    "Elasticsearch": ("Elasticsearch", "ElasticSearch", "elasticsearch"),
    "iText": ("iText", "itext", ),
    "Dask": ("Dask", "dask"),
    "Immutable.js": ("Immutable.js", "immutable.js",),
    "RxJS": ("RxJS", "rxJS",),
    "Stanford CoreNLP": ("Stanford CoreNLP", "Stanford coreNLP",),
    "OpenNLP": ("OpenNLP", "openNLP",),
    "NLTK": ("NLTK", "nltk",),
    "EventMachine": ("EventMachine", "eventMachine",),
    "Socket.IO": ("Socket.IO", "socket.IO",),
    "Axios": ("Axios", "axios"),
    "Leaflet.js": ("Leaflet.js", "leaflet.js"),
    "leaflet-google.js": ("leaflet-google.js", "leaflet-google", "leaflet google")
}
fw_collection = {
    "Flask": ("Flask", "flask"),
    "Django": ("Django", "django"),
    "Django Rest Framework": ("Django Rest Framework", "DRF"),
    "Angular": ("Angular", "AngularJS", "Angular.js", "angular", ),
    "Ruby on Rails": ("Ruby on Rails", "Rails", "RoR", "ruby-on-rails"),
    "Laravel": ("Laravel", "Laravel 5"),
    "Vue.js": ("Vue.js", "VueJS", "Vue"),
    "Vuetify": ("Vuetify", "vuetify",),
    "ASP.NET": ("ASP.NET", ".NET", ".net", ".Net"),
    "React Native": ("React Native", "React native"),
    "PHPUnit": ("PHPUnit", "PHPunit"),
    "Ember.js": ("Ember.js", "Ember", "ember", "EmberJs", "ember.js"),
    "Mocha": ("Mocha", "mocha"),
    "Flutter": ("Flutter", "flutter"),
    "MyBatis": ("MyBatis", "mybatis"),
    "Cypress": ("Cypress", "Cypress.io"),
    "Selenium": ("Selenium", "selenium"),
    "JAXB": ("JAXB", "Jaxb"),
    "Jest": ("Jest", "jest"),
    "Apache Spark": ("Apache Spark", "Spark", "spark"),
    "WatchKit": ("WatchKit", "watchKit",),
    "XCTest": ("XCTest", "XCtest",),
    "Web Forms": ("Web Forms", "WebForms",),
    "Express.js": ("Express.js", "Express"),
    "Hadoop": ("Hadoop", "hadoop"),
    "Ext.js": ("Ext.js", "Extjs", "ExtJS"),
    "Foundation": ("Foundation", ),
    "Drupal": ("Drupal", "drupal", "drupal-8"),
    "knockout": ("knockout", "knockout.js", "KnockoutJS")
}
ds_collection = {
    "Relational Database": ("Relational Database", "relational database", "Relational database"),
    "Non-relational Database": ("Non-relational Database", "non-relational database", "Non-relational database"),
    "NoSQL": ("NoSQL", "nosql", "NoSql"),
    "MySQL": ("MySQL", "mysql", "Mysql"),
    "InnoDB": ("InnoDB", "innodb"),
    "PostgreSQL": ("PostgreSQL", "Postgresql", "Postgres", "postgresql"),
    "MariaDB": ("MariaDB", "Mariadb"),
    "Oracle": ("Oracle", "oracle"),
    "ClustrixDB": ("ClustrixDB", "clustrixdb"),
    "MongoDB": ("MongoDB", "mongodb", "mongo", "Mongo"),
    "DynamoDB": ("DynamoDB", "Dynamo"),
    "Redis": ("Redis", "redis"),
    "Microsoft SQL Server": ("Microsoft SQL Server", "MS SQL", "MSSQL", "mssql"),
    "Apache Phoenix": ("Apache Phoenix", "Phoenix"),
    "Memcached": ("Memcached", "memcached"),
    "Apache HBase": ("Apache HBase", "HBase"),
    "Apache Cassandra": ("Apache Cassandra", "Cassandra"),
    "Firebase": ("Firebase", "firebase"),
    "Firestore": ("Firestore", "firestore"),
    "Presto": ("Presto", "PrestoDB"),
    "RTDB": ("RTDB", "rtdb"),
    "Varnish": ("Varnish", "VARNISH"),
    "SQL Server": ("SQL Server", "sql-server"),
}
dt_collection = {
    "JSON": ("JSON", "json"),
    "RabbitMQ": ("RabbitMQ", "rabbitMQ"),
    "Kafka": ("Kafka", "kafka"),
    "Data Pipeline": ("Data Pipeline", "data pipelines", "Data pipelines"),
}
os_collection = {
    "Linux": ("Linux", "linux"),
    "Ubuntu": ("Ubuntu", "ubuntu"),
    "Android": ("Android", "android"),
    "iOS": ("iOS", "ios"),
    "Windows": ("Windows", "windows"),
    "Windows Server": ("Windows Server", "windows server"),
    "CentOS": ("CentOS", "centOS"),
    "Redhat": ("Redhat", "redhat"),
    "macOS": ("macOS", "MacOS", "OS X"),
    "Unix": ("Unix", "unix"),
    "Virtual Machine": ("Virtual Machine", "virtual machine", "virtual machines", "VM"),
    "LXC": ("LXC", "lxc")
}
sv_collection = {
    "Nginx": ("Nginx", "nginx"),
    "Node.js": ("Node.js", "node.js", "NodeJS", "Node", "node", "Nodejs", "Node.JS"),
    "Jetty": ("Jetty", "jetty"),
    "CDN": ("CDN", "cdn"),
    "Cluster": ("Cluster", "cluster", "clusters")
}
tl_collection = {
    "Jenkins": ("Jenkins", "jenkins"),
    "Gradle": ("Gradle", "gradle"),
    "npm": ("npm", "NPM"),
    "Maven": ("Maven", "maven"),
    "RubyGems": ("RubyGems", "rubygems"),
    "Git": ("Git", "git"),
    "Subversion": ("Subversion", "subversion",),
    "Grunt": ("Grunt", "grunt"),
    "Slack": ("Slack", "slack"),
    "WordPress": ("WordPress", "wordpress", "Wordpress"),
    "Jetpack": ("Jetpack", "jetpack",),
    "WooCommerce": ("WooCommerce", "Woocommerce",),
    "webpack": ("webpack", "Webpack"),
    "Aspose": ("Aspose", "Aspose API"),
    "debugger": ("Debugger", "debugger"),
    "IDE": ("IDE", "ide"),
    "IntelliJ IDEA": ("IntelliJ IDEA",),
    "Skype": ("Skype", "skype"),
    "Photoshop": ("Photoshop", "photoshop"),
    "PayPal": ("PayPal", "paypal"),
    "Stripe": ("Stripe", "stripe"),
    "Pivotal Tracker": ("Pivotal Tracker", "pivotal tracker"),
    "AVA": ("AVA", "ava",),
    "Terraform": ("Terraform", "terraform"),
    "Ansible": ("Ansible", "ansible",),
    "Matillion": ("Matillion", "matillion"),
    "Bugzilla": ("Bugzilla", "bugzilla"),
    "JIRA": ("JIRA", "Jira"),
    "AppKit": ("AppKit", "Appkit"),
    "Crashlytics": ("Crashlytics", "crashlytics"),
    "Bitrise": ("Bitrise", "bitrise",),
    "Fastlane": ("Fastlane", "fastlane",),
    "Zeplin": ("Zeplin", "zeplin",),
    "Wireframes": ("Wireframes", "wireframes",),
    "Trello": ("Trello", "trello"),
    "DeepDive": ("DeepDive", "Deepdive",),
    "Google Hangouts": ("Google Hangouts", "Google hangouts",),
    "Saltstack": ("Saltstack", "saltstack",),
    "Codeship": ("Codeship", "codeship"),
    "Mapbox": ("Mapbox", "mapbox"),
    "ESRI": ("ESRI", "esri"),
    "Visual Studio": ("Visual Studio", "Visual studio", "visual-studio-2019", "visual-studio-2017", "visual-studio"),
    "productivity tools": ("productivity tools", "Productivity tools",),
    "Vagrant": ("Vagrant", "vagrant"),
    "Puppet": ("Puppet", "puppet")
}
at_collection = {
    "REST": ("REST", "RESTful API", "RESTful APIs", "REST API", "REST APIs", "RESTful", "Restful APIs",
             "Representational state transfer"),
    "microservices": ("microservices", "Microservices", "Microservice", "microservice"),
    "message-based communication": ("message-based communication",),
    "serverless": ("serverless", "Serverless"),
    "distributed systems": ("distributed systems", "Distributed systems", "distributed-system"),
    "Zookeeper": ("Zookeeper", "zookeeper"),
    "MVC": ("MVC", "mvc"),
    "MVVM": ("MVVM", "mvvm"),
    "cloud architecture": ("cloud architecture", "Cloud architecture"),
    "Flux": ("Flux", "flux", ),
    "LAMP": ("LAMP", "Lamp"),
    "Middleware": ("Middleware", "middleware"),
    "Architecture": ("Architecture", "architecture"),
    "architecture diagrams": ("architecture diagrams",),
    "architecture review": ("architecture review", "architecture reviews"),
}
ap_collection = {
    "Agile": ("Agile", "agile"),
    "Scrum": ("Scrum", "scrum", "SCRUM"),
    "Extreme Programming": ("Extreme Programming", "XP", ),
    "Kanban": ("Kanban", "kanban", "KANBAN"),
    "GitFlow": ("GitFlow", "Gitflow", "gitflow"),
    "Continuous Integration": ("Continuous Integration", "CI", "Continuous integration", "continuous integration",
                               "continuous-integration"),
    "Continuous Delivery": ("Continuous Delivery", "CD", "continuous delivery"),
    "Continuous Deployment": ("Continuous Deployment", "Continuous Deployments", "continuous deployment"),
    "Sprint": ("Sprint", "sprint", "sprints"),
    "CI/CD": ("CI/CD", "CD/CI"),
    "Test-driven development": ("Test-driven development", "TDD", "test-driven development"),
    "automated testing": ("automated testing", "automated tests", "automated-tests", "automated test"),
    "test automation": ("test automation", "Test automation"),
    "E2E testing": ("E2E testing", "End-to-End testing"),
    "continuous testing": ("continuous testing", "Continuous testing"),
    "Unit testing": ("Unit testing", "unit testing", "Unit Testing", "unit tests", "Unit Tests", "unit test"),
    "Integration Testing": ("Integration Testing",),
    "Automated Configuration": ("Automated Configuration", "Automated configuration"),
    "Automatic Backups": ("Automatic Backups", ),
    "build automation": ("build automation", "Build automation"),
    "object-oriented design": ("object-oriented design", "object-oriented software development"),
    "Waterfall model": ("Waterfall", "waterfall"),
    "pair-programming": ("pair-programming", "Pair-programming"),
    "peer review": ("peer review", "peer reviews", ),
    "code-review": ("code-review", "code-reviews", "code reviews", "code review"),
    "SOLID": ("SOLID", "SOLID principle", ),
    "DRY": ("DRY", "DRY principle"),
    "DDD": ("DDD", "DDD principle"),
    "KISS": ("KISS", "KISS principle"),
    "technical principles": ("technical principles", "Technical principles", ),
    "development techniques": ("development techniques", "Development techniques",),
    "auto-scaling": ("auto-scaling", "Auto-scaling", ),
    "regression test": ("regression test", "Regression Test"),
    "testing principles": ("testing principles", "Testing principles",),
    "UITests": ("UITests", "UItests",),
    "software reliability analyses": ("software reliability analyses", "Software reliability analyses")
}
se_collection = {
    "Design Patterns": ("Design Patterns", "design patterns"),
    "logging": ("logging", "Logging"),
    "profiling": ("profiling", "Profiling"),
    "integration": ("integration", "integrations", "integrate", ),
    "refactoring": ("refactoring", "Refactoring"),
    "documentation": ("documentation", "Documentation"),
    "database migrations": ("database migrations", "Database migrations"),
    "caching": ("caching", "Caching"),
    "debugging": ("debugging", "Debugging"),
    "scaling": ("scaling", "scaling"),
    "testing": ("testing", "Testing"),
    "planning": ("planning", "plan"),
    "designing": ("designing", "Designing"),
    "Modular Design": ("Modular Design", "modular design"),
    "developing": ("developing", "develop"),
    "maintaining": ("maintaining", "Maintaining", "maintain"),
    "performance analysis": ("performance analysis", "Performance analysis",),
    "optimisation": ("optimisation", "optimisations", "optimize"),
    "performance optimization": ("performance optimization", "performance optimisation", "Performance Optimization",
                                 "performance improvement", "performance improvements"),
    "Deployment": ("Deployment", "deployment", "deployments"),
    "Version Control": ("Version Control", "version control", "VCS", "Source Control", "Source control",
                        "source control", "Source Code Control", "Source Code Management",),
    "Troubleshooting": ("Troubleshooting", "troubleshooting"),
    "monitoring": ("monitoring", "Monitoring"),
    "maintenance": ("maintenance", "Maintenance"),
    "support": ("support", "Support"),
    "merging": ("merging", "Merging"),
    "message queueing": ("message queueing", "Message queueing"),
    "Code optimization": ("Code optimization", "Code optimization"),
    "enhance": ("enhance", "enhancing"),
    "implementation": ("implementation", "Implementation"),
    "client-side routing": ("client-side routing", ),
    "dynamic code loading": ("dynamic code loading", ),
    "code branching": ("code branching", "branching", ),
    "fixing bugs": ("fixing bugs", "Fixing bugs"),
    "quality improvements": ("quality improvements", "Quality improvements"),
    "tech debt balance": ("tech debt balance", "Tech debt balance"),
    "Tech Debt": ("Tech Debt", "tech debt"),
    "engineering standards": ("engineering standards", "Engineering standards"),
    "performance issues": ("performance issues", "Performance issues", ),
    "troubleshoot complex issues": ("troubleshoot complex issues", "Troubleshoot complex issues", ),
    "roadmap priorities": ("roadmap priorities", "Roadmap priorities",),
    "functional requirements": ("functional requirements", "Functional requirements", ),
    "design specifications": ("design specifications", "Design specifications"),
    "issue-tracking": ("issue-tracking", "Issue-tracking",),
    "Authentication": ("Authentication", "authentication"),
    "Internationalisation": ("Internationalisation", "internationalisation", "internationalization", "Internationalization",),
    "stream processing": ("stream processing", "Stream processing",),
    "data processing": ("data processing", "Data processing",),
    "automated processes": ("automated processes", "Automated processes",),
    "rapid iteration": ("rapid iteration", "Rapid iteration",),
    "software engineering": ("software engineering", "Software engineering",),
    "software development life cycle": ("software development life cycle", "Software development life cycle",),
    "Load Balancing": ("Load Balancing", "Load balancing",),
    "design mockups": ("design mockups", "Design mockups",),
    "technical feasibility": ("technical feasibility", "Technical feasibility",),
    "design concepts": ("design concepts", "Design concepts",),
    "Performance Tweaking": ("Performance Tweaking", "performance tweaking"),
    "Infrastructure Design": ("Infrastructure Design", "infrastructure design"),
    "Data Modelling": ("Data Modelling", "data modelling"),
    "User Experience": ("User Experience", "User Experiences",),
}
pf_collection = {
    "Cloud Platforms": ("Cloud Platforms", "Cloud platforms"),
    "cloud-based systems": ("cloud-based systems", "cloud-based systems"),
    "cloud services": ("cloud services", "Cloud services", "Cloud Servers", "cloud"),
    "AWS": ("AWS", "aws", "Amazon Web Services", "amazon-web-services"),
    "GCP": ("GCP", "Google Cloud Platform", "GOOGLE CLOUD", "Google Cloud", "google-cloud-platform"),
    "Azure": ("Azure", "Microsoft Azure", "azure", ),
    "Heroku": ("Heroku", "heroku"),
    "DigitalOcean": ("DigitalOcean", "Digitalocean"),
    "GitHub": ("GitHub", "github", "Github"),
    "GitLab": ("GitLab", "gitLab", "gitlab"),
    "Docker": ("Docker", "docker"),
    "Kubernetes": ("Kubernetes", "kubernetes"),
    "Unity": ("Unity", "unity"),
    "Bitbucket": ("Bitbucket", "bitbucket"),
    "Apache Solr": ("Apache Solr", "Solr"),
    "Amazon Redshift": ("Amazon Redshift", "Amazon redshift", "Redshift"),
    "Amazon S3": ("Amazon S3", "S3", "s3"),
    "AWS Glue": ("AWS Glue", "AWS glue"),
    "AWS Pipeline": ("AWS Pipeline", "AWS pipeline"),
    "Amazon EC2": ("Amazon EC2", "EC2", "ec2"),
    "Amazon RDS": ("Amazon RDS", "RDS", "AWS RDS"),
    "BrowserStack": ("BrowserStack", "browserstack"),
    "Google APIs": ("Google APIs", "Google API", ),
    "Athena": ("Athena", "Athena",),
    "Ionic": ("Ionic", ),
    "Snowflake": ("Snowflake", "snowflake"),
    "Looker": ("Looker", "looker"),
    "Apache Arrow": ("Apache Arrow",),
    "Xamarin": ("Xamarin",),
    "Amazon Turk": ("Amazon Turk",),
    "VPC": ("VPC", "vpc",),
    "Amazon Route 53": ("Amazon Route 53", "Route53", "route53",),
    "AWS Lambda": ("AWS Lambda", "Lambda", "lambda"),
    "Amazon CloudFront": ("Amazon CloudFront", "CloudFront", "Cloudfront"),
    "Amazon SNS": ("Amazon SNS", "SNS", "sns"),
    "AWS Elastic Beansalk": ("AWS Elastic Beansalk", "Elastic Beansalk",),
    "AWS API Gateway": ("AWS API Gateway", "aws-api-gateway"),
    "Packer": ("Packer", "packer")
}
dv_collection = {
    "Front-end": ("Front-end", "frontend", "front-end development", "front-end", "Frontend"),
    "Back-end": ("Back-end", "Backend", "backend", "back-end", "backends", "back end"),
    "Full Stack": ("Full Stack", "full stack", "Full-stack"),
    "Security": ("Security", "security"),
    "QA": ("QA", "qa"),
    "Product Management": ("Product Management", "product management"),
    "UI": ("UI", "UIs", "UI designs"),
    "UX": ("UX", "UXs"),
    "UI/UX": ("UI/UX", "UI/UX Design", "UI/UX design", "UX/UI"),
    "Design": ("Design", "design"),
    "DevOps": ("DevOps", "Devops", "devops", "dev ops"),
    "Big Data": ("Big Data", "Big data", "large-scale data", "Large-scale data", "large datasets", "Large datasets"),
    "3D Animation": ("3D Animation", "3D animation"),
    "Image Processing": ("Image Processing", ),
    "Data Analytics": ("Data Analytics", "data analytics"),
    "Data Science": ("Data Science", "data science", "Data science"),
    "Site Reliability": ("Site Reliability", "site reliability", ),
    "Data Infrastructure": ("Data Infrastructure", "data infrastructure"),
    "Network Infrastructure": ("Network Infrastructure", "network infrastructure", "Network infrastructure",),
    "Large-scale network": ("Large-scale network", "large-scale network"),
    "Infrastructure Engineering": ("Infrastructure Engineering", "infrastructure engineering"),
    "Automation": ("Automation", "automation",),
    "cloud-security": ("cloud-security", "Cloud Platform Security", "Cloud Platform security")
}
ps_collection = {
    "Front-end Engineer": ("Front-end Engineer", "Front-end Engineer", "frontend engineers", "Frontend Engineers",
                           "Front-End Engineer"),
    "Front-end Developer": ("Front-end Developer", "front-End Developer", "front end developer", "Frontend Developers",
                            "front-end developers", "FRONT END WEB DEVELOPER", "Front End Developer"),
    "Back-end Engineer": ("Back-end Engineer", "back-end Engineers", "Back End Engineers", "Backend Software Engineer",
                          "back-end engineer", "Back-End Software Engineer"),
    "Back-end Developer": ("Back-end Developers", "Back End Developers", "back-end developers", "Back-End Developer",
                           "back-end developer", "Backend Developer"),
    "Full Stack Engineer": ("Full Stack Engineer", "Full-Stack Engineer", "full stack engineer", "full-stack engineer",
                            "Full Stack Software Engineers"),
    "Full Stack Developer": ("Full Stack Developer", "full stack software developer", "full stack developers",
                             "Full Stack Developers", "full-stack developers", "Full Stack developer"),
    "Software Developer": ("Software Developer", "software developer"),
    "Software Engineer": ("Software Engineer", "Software Engineers", "software engineer"),
    "Software Architect": ("Software Architect", "Architect", "architect", "architects", ),
    "Senior Software Architect": ("Senior Software Architect", "Senior Software Architects"),
    "Web Developer": ("Web Developer", "web developer"),
    "DevOps Engineer": ("DevOps Engineer", "DevOps Engineers", "DevOps engineers"),
    "Android Developer": ("Android Developer", "Android Developers"),
    "Android Engineer": ("Android Engineer", "Android engineer"),
    "Game Developer": ("Game Developer", "Game developer"),
    "Data Engineer": ("Data Engineer", "Data Engineers", "data engineer"),
    "Data Developer": ("Data Developer", "Data Developers"),
    "Data Scientist": ("Data Scientist", "data scientist", "data scientists"),
    "Data Analyst": ("Data Analyst", "Data Analysts"),
    "Product Manager": ("Product Manager", "product manager", "product managers", "PM", "Product Managers"),
    "Project Manager": ("Project Manager", "project manager", "Technical Project Manager"),
    "Product Designer": ("Product Designer", "Product Designers", "product designers"),
    "Designer": ("Designer", "Designers", "designers", "designer"),
    "UI/UX Designer": ("UI/UX Designer", "UI/UX designer"),
    "UX Engineer": ("UX Engineer", "UX Engineers"),
    "QA Tester": ("QA Tester", "QA tester"),
    "QA Engineer": ("QA Engineer", "QA engineer", "QA engineers"),
    "QA Specialist": ("QA Specialist", "QA specialists"),
    "Scrum Master": ("Scrum Master", "Scrum Masters", "Scrum master", "Scrum masters"),
    "Business Analyst": ("Business Analyst", "business analysts"),
    "Software Consultant": ("Software Consultant", "software consultant"),
    "Machine Learning Engineer": ("Machine Learning Engineer", "Machine Learning Engineers"),
    "PHP Developer": ("PHP Developer", "PHP-Developer"),
    "WordPress Developer": ("WordPress Developer", "WordPress developers"),
    "Mobile Engineer": ("Mobile Engineer", "mobile engineer"),
    "React Developer": ("React Developer", "ReactJS Developer"),
    "Desktop Engineer": ("Desktop Engineer", "Desktop engineers"),
    "Developer": ("Developer", "Developers", "developer", "developers"),
    "Senior Back-end Developer": ("Senior Back-end Developer", "Senior Backend Developer", "Senior Backend Developers"),
    "Senior Back-end Engineer": ("Senior Back-end Engineer", "Senior Backend Engineer", "Senior Backend Engineers"),
    "Senior Front-end Developer": ("Senior Front-end Developer", "Senior Frontend Developer", "Senior Frontend Developers"),
    "Senior Front-end Engineer": ("Senior Front-end Engineer", "Senior Frontend Engineer", "Senior Frontend Engineers",
                                  "Senior Front End Engineer", "Senior Front-End Engineer", "Senior Frontend Software Engineer"),
    "Senior Software Developer": ("Senior Software Developer", "Senior Developer", "Senior Developers", "Senior developers",
                                  "senior developer"),
    "Senior Software Engineer": ("Senior Software Engineer", "senior software engineer", "Sr. Software Engineer",
                                 "Senior Engineer", "senior engineer", "Senior Software Engineers", "Senior Engineers"),
    "Senior DevOps Engineer": ("Senior DevOps Engineer", "Sr. DevOps Engineer"),
    "Quality Engineering Manager": ("Quality Engineering Manager", "Quality Engineering Managers"),
    "Software Support Engineer": ("Software Support Engineer", "Software Support Engineers"),
    "Technical Leader": ("Technical Leader", "technical leader"),
    ".NET Developer": (".NET Developer", ".NET developer", ),
    "Ruby on Rails Developer": ("Ruby on Rails Developer", "Ruby on Rails developer", "Rails developer"),
    "Rails Engineer": ("Rails Engineer", "Rails Engineers"),
    "CEO": ("CEO", "ceo"),
    "CTO": ("CTO", "cto"),
    "CFO": ("CFO", "cfo"),
    "Director of Engineering": ("Director of Engineering", "Director of engineering", ),
    "Senior Python Engineer": ("Senior Python Engineer", "senior python engineer", ),
    "iOS Developer": ("iOS Developer", "iOS developer", "iOS developers"),
    "code reviewers": ("code reviewers", "Code reviewers",),
    "Junior Developers": ("Junior Developers", "junior developers", "Jr. Software Developer", "entry-level software developer"),
    "Junior Engineers": ("junior engineers", "junior engineers"),
    "Machine Learning Engineers": ("Machine Learning Engineers", "Machine learning engineers"),
    "Lead Developer": ("Lead Developer", "lead developer", "Lead Application Developer"),
    "Director of Operations": ("Director of Operations", "director of operations"),
    "Senior Systems Developer": ("Senior Systems Developer", "Senior Systems Developers"),
    "Drupal Developer": ("Drupal Developer", "Drupal Developers"),
    "Professional Services Consultant": ("Professional Services Consultant", "Professional Services Consultants"),
    "Lead DevOps Engineer": ("Lead DevOps Engineer", "Lead DevOps engineer", ),
    "System Administrator": ("System Administrator", "system administrator", "sysadmin"),
    "Team Lead": ("Team Lead", "Team lead"),
    "Project Lead": ("Project Lead", "Project lead")
}
cs_collection = {
    "Computer Science": ("Computer Science", "computer science", ),
    "Data Structure": ("Data Structure", "data structure"),
    "Algorithms": ("Algorithms", "algorithms"),
    "Mathematics": ("Mathematics", "mathematics"),
    "Statistics": ("Statistics", "statistics"),
    "Concurrency": ("Concurrency", "concurrency", "concurrent programming"),
    "Parallelism": ("Parallelism", "parallelism"),
    "Object-oriented Programming": ("Object-oriented Programming", "object-oriented programming", "OOP"),
    "Asynchronous": ("Asynchronous", "asynchronous"),
    "Cryptography": ("Cryptography", "cryptography"),
    "Computability": ("Computability", "computability"),
    "Computer Architecture": ("Computer Architecture", "computer architecture"),
    "Chunking": ("Chunking", "chunking"),
    "Ethernet": ("Ethernet", "ethernet"),
    "DNS": ("DNS", "dns"),
    "VPN": ("VPN", "vpn"),
    "Networking": ("Networking", "networking"),
    "Network": ("Network", "networks", "network"),
    "Routing": ("Routing", "routing"),
    "routers": ("routers", "Routers"),
    "switches": ("switches", "Switches"),
    "PoP": ("PoP", "POP"),
    "Virtual LAN": ("Virtual LAN", "VLANs"),
    "Computational Complexity": ("Computational Complexity", "computational complexity")
}
ai_collection = {
    "AI": ("AI", "artificial intelligence"),
    "Machine Learning": ("Machine Learning", "Machine learning", "machine learning", "machine-learning"),
    "Deep Learning": ("Deep Learning", "Deep learning"),
    "NLP": ("NLP", "Natural Language Processing", "natural language processing"),
    "Text Classification": ("Text Classification", "text classification"),
    "Sentiment Analysis": ("Sentiment Analysis", "sentiment analysis", "Sentiment analysis"),
    "NER": ("NER", "named-entity recognition"),
    "CNN": ("CNN", "convolutional neural network"),
    "Transfer Learning": ("Transfer Learning", "transfer learning"),
    "artificial general intelligence": ("artificial general intelligence",),
    "AI Ethics": ("AI Ethics", "ai Ethics"),
    "model training": ("model training", "training", ),
    "labelling": ("labelling", "Labelling"),
    "Bayesian Forecasting Models": ("Bayesian Forecasting Models", "Bayesian forecasting models"),
    "computer vision": ("computer vision", "computer-vision", )
}
pt_collection = {
    "Messaging Protocols": ("Messaging Protocols", "messaging protocols", ),
    "Protocol Buffers": ("Protocol Buffers", "protocol buffers"),
    "TCP": ("TCP", "tcp"),
    "TCP/IP": ("TCP/IP", "tcp/ip"),
    "IP": ("IP", "ip"),
    "UDP": ("UDP", "udp"),
    "HTTP": ("HTTP", "http"),
    "HTTPs": ("HTTPs", "https"),
    "WebSocket": ("WebSocket", "WebSockets"),
    "API": ("API", "APIs", "api"),
    "CORS": ("CORS", "cors"),
    "SSL": ("SSL", "ssl"),
    "SSH": ("SSH", "ssh"),
    "Paxos": ("Paxos", "paxos"),
    "FTP": ("FTP", "ftp"),
    "SFTP": ("SFTP", "sftp"),
    "TLS": ("TLS", "tls"),
    "SOAP": ("SOAP", "soap"),
    "BGP": ("BGP", "bgp"),
    "Contentful": ("Contentful", "contentful"),
    "DHCP": ("DHCP", "dhcp"),
    "VRRP": ("VRRP", "vrrp"),
    "VLANs": ("VLANs", "vlans"),
    "IGP": ("IGP", "igp"),
    "ECMP": ("ECMP", "ecmp"),
    "OSPF": ("OSPF", "ospf"),
    "MPLS": ("MPLS", "mpls"),
    "RSVP": ("RSVP", "rsvp"),
    "LDP": ("LDP", "ldp"),
    "APN": ("APN", "apn"),
    "SNMP": ("SNMP", "snmp")
}

pd_collection = {
    "Web application": ("Web application", "web application", "web applications", "web-app", "web apps", "web services",
                        "web technology", "web technologies", "website", "websites", "web", "Web", "web-technology",
                        "web-services"),
    "single-page application": ("single-page application", "single-page-application", "single page application", "SPA"),
    "Software as a service": ("Software as a service", "SaaS", "SAAS", "SaaS technology"),
    "Enterprise Applications": ("Enterprise Applications", "enterprise applications", "enterprise class applications",),
    "Open-source software": ("Open-source software", "open source", "open-source", "Open source"),
    "Mobile app": ("Mobile app", "Mobile", "mobile", "mobile platform", "mobile applications", "mobile app"),
    "Desktop Application": ("Desktop Application", "desktop", "Desktop"),
    "Small and Medium Scale Systems": ("Small and Medium Scale Systems", "Small and medium scale systems",),
    "Large-scale systems": ("Large-scale systems", "large-scale systems", ),
    "third party technologies": ("third party technologies", "Third party technologies", "third-party checkout",
                                 "third-party APIs", "third-party billing services"),
    "high traffic applications": ("high traffic applications", "High traffic applications",),
    "Analysis Engines": ("Analysis Engines", "analysis engines", "Analysis engines",),
    "data driven application": ("data driven application", "data driven applications", "data-oriented products"),
    "profitable project": ("profitable project", "profitable projects"),
    "Legacy System": ("Legacy System", "legacy system"),
    "Video Games": ("Video Games", "video games")
}

ql_collection = {
    "Technical Best Practices": ("Technical Best Practices", "technical best practises", "best practices", ),
    "Coding Standards": ("Coding Standards", "coding standards"),
    "Scalability": ("Scalability", "scalability", ),
    "Testability": ("Testability", "testability"),
    "high-quality code": ("high-quality code",),
    "Reliability": ("Reliability", "reliability", "reliable code",),
    "High Performance": ("High Performance", "high-performance", "high performance code", "performance"),
    "Supportability": ("Supportability", "supportability"),
    "Maintainability": ("Maintainability", "maintainability"),
    "Modularity": ("Modularity", "modularity"),
    "Ambiguity": ("Ambiguity", "ambiguity"),
    "Data Integrity": ("Data Integrity", "data integrity"),
    "Code Quality": ("Code Quality", "code quality"),
    "High Quality": ("High Quality", "high quality", "High quality",),
    "speed": ("speed", "maximum speed"),
    "Consistency": ("Consistency", "consistency"),
    "Accessibility": ("Accessibility", "accessibility"),
    "High Availability": ("High Availability", "High availability", "highly-available"),
    "reusable code": ("reusable code", "Reusable code", ),
    "maintainable systems": ("maintainable systems", "Maintainable systems",),
    "system performance": ("system performance", "System performance",),
    "cross-browser compatibility": ("cross-browser compatibility", "Cross-browser compatibility",),
    "cross-device compatibility": ("cross-device compatibility", "Cross-device compatibility",),
    "efficient processes": ("efficient processes", "Efficient processes",),
    "high-quality software": ("high-quality software", "High-quality software")
}
