pl_collection = {
    "JavaScript": ("JavaScript", "Javascript", "javascript", "JS"),
    "ECMAScript": ("ECMAScript", "ecmascript", "ES2015", "ES2016", "ES2017", "ES2018", "ES5", "ES6", "ES7", "ES8"),
    "TypeScript": ("TypeScript", "Typescript", "typescript"),
    "Java": ("Java", "java", "Java8", "Java11"),
    "Python": ("Python", "python"),
    "Ruby": ("Ruby", "ruby"),
    "PHP": ("PHP", "php", "PHP7"),
    "C": ("C", "c"),
    "C++": ("C++", "c++"),
    "C#": ("C#", "c#"),
    "Objective-C": ("Objective-C", "Objective C", "objective-c", "Obj-C"),
    "Swift": ("Swift", "swift"),
    "Kotlin": ("Kotlin", "kotlin"),
    "Go": ("Go", "go", "Golang"),
    "Rust": ("Rust", "rust"),
    "Perl": ("Perl", "perl"),
    "Erlang": ("Erlang", "erlang"),
    "Groovy": ("Groovy", "groovy"),
    "JVM": ("JVM", "jvm"),
    "Scala": ("Scala", "scala"),
    "Elixir": ("Elixir", "elixir"),
    "Cython": ("Cython", "cython", "CPython", "CPython"),
    "Jython": ("Jython", "jython"),
    "Clojure": ("Clojure", "clojure"),
    "Lua": ("Lua", "lua"),
    "DSLs": ("DSLs", )
}
ol_collection = {
    "HTML": ("HTML", "html", "HTML5"),
    "CSS": ("CSS", "css", "CSS3"),
    "XML": ("XML", "xml"),
    "Bash": ("Bash", "bash", "Bash Shell"),
    "SCSS": ("SCSS", "scss"),
    "SASS": ("SASS", "sass"),
    "GraphQL": ("GraphQL", "graphQL"),
    "SQL": ("SQL", "sql")
}
lb_collection = {
    "React": ("React", "react", "React.js", "react.js", "React JS", "ReactJS", "React Hooks"),
    "Redux": ("Redux", "redux"),
    "jQuery": ("jQuery", "jquery", "JQuery", "Jquery"),
    "Pandas": ("Pandas", "pandas"),
    "Numpy": ("Numpy", "numpy"),
    "SciPy": ("SciPy", "scipy"),
    "scikit-learn": ("scikit-learn", "Scikit-learn"),
    "Matplotlib": ("Matplotlib", "matplotlib"),
    "Pytorch": ("Pytorch", "pytorch", "torch"),
    "Scrapy": ("Scrapy", "scrapy"),
    "PySpark": ("PySpark", "Pyspark"),
    "Spring": ("Spring", "spring"),
    "Spring Boot": ("Spring Boot", "Spring boot"),
    "Bootstrap": ("Bootstrap", "bootstrap"),
    "Elasticsearch": ("Elasticsearch", "elasticsearch")
}
fw_collection = {
    "Flask": ("Flask", "flask"),
    "Django": ("Django", "django"),
    "Angular": ("Angular", "AngularJS"),
    "Laravel": ("Laravel", "Laravel 5"),
    "Vue": ("Vue", "VueJS"),
    "ASP.NET": ("ASP.NET", ".NET"),
    "React Native": ("React Native", "React native"),
    "PHPUnit": ("PHPUnit", "PHPunit"),
    # "Ember": ("Ember", "ember")
    "Mocha": ("Mocha", "mocha"),
    "Flutter": ("Flutter", "flutter")
}
ds_collection = {
    "relational database": ("relational database", "Relational database"),
    "non-relational database": ("non-relational database", "Non-relational database"),
    "NoSQL": ("NoSQL", "nosql"),
    "MySQL": ("MySQL", "mysql"),
    "InnoDB": ("InnoDB", "innodb"),
    "PostgreSQL": ("PostgreSQL", "Postgresql", "Postgres"),
    "MariaDB": ("MariaDB", "Mariadb"),
    "Oracle": ("Oracle", "oracle"),
    "ClustrixDB": ("ClustrixDB", "clustrixdb"),
    "MongoDB": ("MongoDB", "mongodb", "mongo"),
    "DynamoDB": ("DynamoDB", "Dynamo"),
    "Redis": ("Redis", "redis"),
    "Microsoft SQL Server": ("Microsoft SQL Server", "MS SQL", "MSSQL", "mssql"),
    "Apache Phoenix": ("Apache Phoenix", "Phoenix"),
    "Memcached": ("Memcached", "memcached"),
    "Apache HBase": ("Apache HBase", "HBase"),
    "Apache Cassandra": ("Apache Cassandra", "Cassandra"),
    "Firebase": ("Firebase", "firebase"),
    "Presto": ("Presto", "PrestoDB")
}
dt_collection = {
    "JSON": ("JSON", "json"),
    "RabbitMQ": ("RabbitMQ", "rabbitMQ"),
    "Kafka": ("Kafka", "kafka"),

}
os_collection = {
    "Linux": ("Linux", "linux"),
    "Ubuntu": ("Ubuntu", "ubuntu"),
    "Android": ("Android", "android"),
    "iOS": ("iOS", "ios"),
    "Windows": ("Windows", "windows"),
    "Windows Server": ("Windows Server", "windows server"),
    "CentOS": ("CentOS", "centOS"),
    "Redhat": ("Redhat", "redhat"),
    "macOS": ("macOS", "MacOS", "OS X"),
    "Unix": ("Unix", "unix"),
}
sv_collection = {
    "Nginx": ("Nginx", "nginx"),
    "Node.js": ("Node.js", "node.js", "NodeJS", "Node", "node"),
    "Jetty": ("Jetty", "jetty"),
    "CDN": ("CDN", "cdn")
}
tl_collection = {
    "Jenkins": ("Jenkins", "jenkins"),
    "Gradle": ("Gradle", "gradle"),
    "Maven": ("Maven", "maven"),
    "Git": ("Git", "git"),
    "Grunt": ("Grunt", "grunt"),
    "Slack": ("Slack", "slack"),
    "WordPress": ("WordPress", "wordpress"),
    "webpack": ("webpack", "Webpack"),
    "Aspose": ("Aspose", "Aspose API"),
    "debugger": ("Debugger", "debugger"),
    "IDE": ("IDE", "ide"),
    "IntelliJ IDEA": ("IntelliJ IDEA",),
    "Skype": ("Skype", "skype"),
    "Photoshop": ("Photoshop", "photoshop"),
    "PayPal": ("PayPal", "paypal"),
    "Stripe": ("Stripe", "stripe")
}
at_collection = {
    "Representational state transfer": ("RESTful APIs", "REST API", "REST APIs", "RESTful", "REST"),
    "microservices": ("microservices", "Microservices", "Microservice"),
    "serverless": ("serverless", "Serverless"),
    "distributed systems": ("distributed systems", "Distributed systems"),
    "Zookeeper": ("Zookeeper", "zookeeper"),
    "MVC": ("MVC", "mvc"),
    "cloud architecture": ("cloud architecture", "Cloud architecture")
}
ap_collection = {
    "Agile": ("Agile", "agile"),
    "Scrum": ("Scrum", "scrum", "SCRUM"),
    "Extreme Programming": ("XP", "Extreme Programming"),
    "Kanban": ("Kanban", "kanban"),
    "GitFlow": ("GitFlow", "Gitflow", "gitflow"),
    "Continuous Integration": ("Continuous Integration", "CI", "Continuous integration"),
    "Continuous Delivery": ("Continuous Delivery", "CD", "continuous delivery"),
    "Sprint": ("Sprint", "sprint"),
    "CI/CD": ("CI/CD", ),
    "Test-driven development": ("Test-driven development", "TDD", "test-driven development"),
    "automated testing": ("automated testing", "'automated tests"),
    "object-oriented design": ("object-oriented design", ),
    "Waterfall model": ("Waterfall", "waterfall"),
    "pair-programming": ("pair-programming", "Pair-programming"),
    "peer review": ("peer review", ),
    "SOLID": ("SOLID", ),
    "DRY": ("DRY", ),
    "DDD": ("DDD", ),
    "KISS": ("KISS", ),
}
se_collection = {
    "logging": ("logging", "Logging"),
    "code-review": ("code-review", "code-reviews"),
    "refactoring": ("refactoring", "Refactoring"),
    "documentation": ("documentation", "Documentation"),
    "database migrations": ("database migrations", "Database migrations"),
    "caching": ("caching", "Caching"),
    "debugging": ("debugging", "Debugging"),
    "scaling": ("scaling", "scaling"),
    "testing": ("testing", "Testing"),
    "designing": ("designing", "Designing"),
    "performance optimization": ("performance optimization", ),
    "performance improvement": ("performance improvement", "performance improvements"),
    "deployment": ("deployment", "deployments"),
    "version control": ("version control", "VCS"),
    "source control": ("source control", "Source control"),
    "Troubleshooting": ("Troubleshooting", "troubleshooting"),
    "Unit testing": ("Unit testing", "unit testing"),
    "automated configuration": ("automated configuration", "Automated configuration"),
    "continuous testing": ("continuous testing", "Continuous testing"),
    "build automation": ("build automation", "Build automation"),
    "monitoring": ("monitoring", "Monitoring"),
    "sentiment analysis": ("sentiment analysis", "Sentiment analysis"),
    "maintenance": ("maintenance", "Maintenance"),
    "support": ("support", "Support"),
    "merging": ("merging", "Merging"),
    "message queueing": ("message queueing", "Message queueing"),
    "architecture review": ("architecture review", "architecture reviews"),
    "Code optimization": ("Code optimization", "Code optimization"),
    "enhance": ("enhance", "enhancing"),
    "implementation": ("implementation", "Implementation")
}
pf_collection = {
    "AWS": ("AWS", "aws", "Amazon Web Services"),
    "GCP": ("GCP", "Google Cloud Platform", "GOOGLE CLOUD"),
    "Azure": ("Azure", "Microsoft Azure", "azure"),
    "Heroku": ("Heroku", "heroku"),
    "Github": ("Github", "github"),
    "GitLab": ("GitLab", "gitLab"),
    "Docker": ("Docker", "docker"),
    "Kubernetes": ("Kubernetes", "kubernetes"),
    "Unity": ("Unity", "unity"),
    "cloud services": ("cloud services", "Cloud services"),
    "Bitbucket": ("Bitbucket", "bitbucket"),
    "Apache Solr": ("Apache Solr", "Solr"),
    "Amazon Redshift": ("Amazon Redshift", "Amazon redshift", "Redshift"),
    "S3": ("S3", "s3"),
    "AWS Glue": ("AWS Glue", "AWS glue"),
    "AWS Pipeline": ("AWS Pipeline", "AWS pipeline"),
    "EC2": ("EC2", "ec2"),
    "RDS": ("RDS", "AWS RDS"),

}
dv_collection = {
    "Front-end": ("Front-end", "frontend", "front-end development"),
    "Back-end": ("Back-end", "Backend", "backend"),
    "Full Stack": ("Full Stack", "full stack", "Full-stack"),
    "Software Engineering": ("Software Engineering", "software engineering"),
    "Security": ("Security", "security"),
    "QA": ("QA", ),
    "Product Management": ("Product Management", "product management"),
    "UI": ("UI", "UIs", "UI designs"),
    "UI/UX": ("UI/UX", "UI/UX Design", "UI/UX design"),
    "Design": ("Design", "design"),
    "AI": ("AI", "artificial intelligence"),
    "DevOps": ("DevOps", "Devops", "devops"),
    "Big Data": ("Big Data", "Big data"),
    "Computer Vision": ("Computer Vision", "computer vision"),
    "3D Animation": ("3D Animation", "3D animation"),
    "Data Analytics": ("Data Analytics", "data analytics"),
}
ps_collection = {
    "Front-end Engineer": ("Front-end Engineer", "Front-end Engineer", "frontend engineers"),
    "Front-end Developer": ("Front-end Developer", "front-End Developer", "front end developer", "Frontend Developers",
                            "front-end developers", "FRONT END WEB DEVELOPER"),
    "Back-end Engineer": ("Back-end Engineer", "back-end Engineers", "Back End Engineers", "Backend Software Engineer"),
    "Back-end Developer": ("Back-end Developers", "Back End Developers", "back-end developers"),
    "Full Stack Engineer": ("Full Stack Engineer", "full stack engineer", "Full Stack Software Engineers"),
    "Full Stack Developer": ("Full Stack Developer", "full stack software developer"),
    "Software Developer": ("Software Developer", "software developer"),
    "Software Engineer": ("Software Engineer", "Software Engineers", "software engineer"),
    "Architect": ("Architect", "architect", "architects"),
    "Web Developer": ("Web Developer", "web developer"),
    "DevOps Engineer": ("DevOps Engineer", "DevOps Engineers"),
    "Android Developer": ("Android Developer", "Android Developers"),
    "Android Engineer": ("Android Engineer", "Android engineer"),
    "Game Developer": ("Game Developer", "Game developer"),
    "Data Engineer": ("Data Engineer", "Data Engineers", "data engineer"),
    "Data Developer": ("Data Developer", "Data Developers"),
    "Data Scientist": ("Data Scientist", "data scientist"),
    "Data Analyst": ("Data Analyst", "Data Analysts"),
    "Product Manager": ("Product Manager", "product manager", "PM"),
    "Project Manager": ("Project Manager", "project manager"),
    "Ruby on Rails Developer": ("Ruby on Rails Developer", "Ruby on Rails developer"),
    "Rails Engineer": ("Rails Engineer", "Rails Engineers"),
    "Product Designer": ("Product Designer", "Product Designers", "product designers"),
    "Designer": ("Designer", "Designers", "designers"),
    "UI/UX Designer": ("UI/UX Designer", "UI/UX designer"),
    "UX Engineer": ("UX Engineer", "UX Engineers"),
    "QA Tester": ("QA Tester", "QA tester"),
    "QA Engineer": ("QA Engineer", "QA engineer", "QA engineers"),
    "QA Specialist": ("QA Specialist", "QA specialists"),
    "Scrum Master": ("Scrum Master", "Scrum Masters", "Scrum master", "Scrum masters"),
    "Business Analyst": ("Business Analyst", "business analysts"),
    "Software Consultant": ("Software Consultant", "software consultant"),
    "Machine Learning Engineer": ("Machine Learning Engineer", "Machine Learning Engineers"),
    "PHP Developer": ("PHP Developer", "PHP-Developer"),
    "WordPress Developer": ("WordPress Developer", "WordPress developers"),
    "Mobile Engineer": ("Mobile Engineer", "mobile engineer"),
    "React Developer": ("React Developer", "ReactJS Developer"),
    "Desktop Engineer": ("Desktop Engineer", "Desktop engineers"),
    "Developer": ("Developer", "Developers", "developer", "developers"),
    "Senior Back-end Developer": ("Senior Back-end Developer", "Senior Backend Developer", "Senior Backend Developers"),
    "Senior Back-end Engineer": ("Senior Back-end Engineer", "Senior Backend Engineer", "Senior Backend Engineers"),
    "Senior Front-end Developer": ("Senior Front-end Developer", "Senior Frontend Developer", "Senior Frontend Developers"),
    "Senior Front-end Engineer": ("Senior Front-end Engineer", "Senior Frontend Engineer", "Senior Frontend Engineers",
                                  "Senior Front End Engineer"),
    "Senior Developer": ("Senior Developer", "Senior Developers", "Senior developers"),
    "Senior Software Engineer": ("Senior Software Engineer", "senior software engineer", "Sr. Software Engineer"),
    "Senior DevOps Engineer": ("Senior DevOps Engineer", "Sr. DevOps Engineer"),
    "Quality Engineering Manager": ("Quality Engineering Manager", "Quality Engineering Managers"),
    "Software Support Engineer": ("Software Support Engineer", "Software Support Engineers"),
    "CEO": ("CEO",),
    "CTO": ("CTO", "cto"),
}
cs_collection = {
    "Computer Science": ("Computer Science", "computer science"),
    "Data Structure": ("Data Structure", "data structure"),
    "Algorithms": ("Algorithms", "algorithms"),
    "Mathematics": ("Mathematics", "mathematics"),
    "Statistics": ("Statistics", "statistics"),
    "Concurrency": ("Concurrency", "concurrency"),
    "Parallelism": ("Parallelism", "parallelism"),
    "Object-oriented Programming": ("Object-oriented Programming", "object-oriented programming", "OOP"),
    "Design Patterns": ("Design Patterns", "design patterns"),
    "Asynchronous": ("Asynchronous", "asynchronous"),
    "Cryptography": ("Cryptography", "cryptography"),
    "Computability": ("Computability", "computability"),
    "Computer Architecture": ("Computer Architecture", "computer architecture"),
    "Chunking": ("Chunking", "chunking"),
    "Ethernet": ("Ethernet", ),
    "DNS": ("DNS", ),
    "VPN": ("VPN", )
}
ai_collection = {
    "Machine Learning": ("Machine Learning", "Machine learning"),
    "Deep Learning": ("Deep Learning", "Deep learning"),
    "NLP": ("NLP", "Natural Language Processing", "natural language processing"),
    "Text Classification": ("Text Classification", "text classification"),
    "NER": ("NER", "named-entity recognition"),
    "CNN": ("CNN", "convolutional neural network"),
    "Transfer Learning": ("Transfer Learning", "transfer learning"),
}
pt_collection = {
    "TCP/IP": ("TCP/IP",),
    "UDP": ("UDP", ),
    "HTTP": ("HTTP", "http"),
    "WebSocket": ("WebSocket", "WebSockets"),
    "API": ("API", "APIs"),
    "CORS": ("CORS", ),
    "SSL": ("SSL", ),
    "SSH": ("SSH", ),
    "Paxos": ("Paxos", ),
    "FTP": ("FTP", ),
    "SFTP": ("SFTP", ),
    "TLS": ("TLS", ),
    "SOAP": ("SOAP", ),
    "BGP": ("BGP", ),
}